/**
 * Wortlisten für das Bestarium (epochen- und kategorieabhängig).
 */
window.HTBAH = window.HTBAH || {};

window.HTBAH.ZufallsgeneratorBestienListen = {
  NORM_MITTELALTER: [
    'Wolf',
    'Wildschwein',
    'Bär',
    'Luchs',
    'Fuchs',
    'Dachs',
    'Otter',
    'Biber',
    'Adler',
    'Geier',
    'Schlange',
    'Eber',
    'Hirsch',
    'Reh',
    'Elch',
    'Wisent',
    'Kauz',
    'Uhu',
    'Wildkatze',
    'Marder',
  ],
  NORM_GEGENWART: [
    'Kojote',
    'Waschbär',
    'Wildschwein',
    'Rotfuchs',
    'Marderhund',
    'Nutria',
    'Biber',
    'Seeadler',
    'Wildkatze',
    'Dachs',
    'Igel',
    'Marder',
    'Reh',
    'Damhirsch',
    'Elch',
    'Wolf',
    'Bär',
    'Schwarzbär',
    'Alligator',
    'Python',
  ],
  NORM_ZUKUNFT: [
    'Klontechnischer Schäferhund',
    'Biohybrid-Ratte',
    'Servo-Wächtergeier',
    'Synth-Wolf',
    'Kryo-Biber',
    'Orbital-Möwe',
    'Terraform-Bison',
    'Naniten-Schwarm (insektoid)',
    'Labor-Otter',
    'Ödland-Kojote',
    'Mutationsresistente Wildkatze',
    'Ökosystem-Keiler',
    'Drohnen-Falke (Tiergestalt)',
    'Gen-Reh',
    'Kuppel-Fuchs',
    'Staubwüsten-Geier',
    'Sumpf-Alligator',
    'Röhrenwurm (Riesenform)',
    'Arktis-Schneehase',
    'Savannen-Antilope',
  ],

  FANTASY_MITTELALTER: [
    'Greif',
    'Pegasus',
    'Einhorn',
    'Basilisk',
    'Wyvern',
    'Kitsune',
    'Schimäre',
    'Hippogryph',
    'Kobold-Biest',
    'Schattenwolf',
    'Kristallhirsch',
    'Runenstein-Eber',
    'Mond-Eule',
    'Nebelkatze',
    'Flammenfuchs',
    'Eiswurm',
    'Doppelgänger-Bär',
    'Seelenfalke',
    'Leichenfledermaus',
    'Arkaner Skorpion',
  ],
  FANTASY_GEGENWART: [
    'Urbaner Greif',
    'U-Bahn-Koboldbestie',
    'Smartphone-Besessener Poltergeist-Hund',
    'WLAN-Wyvern',
    'Parkplatz-Chimäre',
    'Straßenbahn-Phantomkatze',
    'Kryptid aus dem Abwasser',
    'Leylinien-Fuchs',
    'Nachtclub-Succubus-Tierling',
    'Energiefeld-Pegasus',
    'Stadtwald-Einhorn',
    'Neon-Basilisk',
    'Hafen-Seeschlange',
    'Urbane Harpyie',
    'Geisterkrähe',
    'Magnetfeld-Wurm',
    'Traumspinne',
    'Aura-Schlange',
    'Ritual-Biest',
    'Okkultes Reptil',
  ],
  FANTASY_ZUKUNFT: [
    'Psi-Drache (Miniatur)',
    'Holomantischer Greif',
    'Quanten-Einhorn',
    'Netrunner-Schlange',
    'Gravitations-Wyvern',
    'Plasma-Fuchs',
    'Hardsuit-Hippogryph',
    'KI-Chimäre',
    'Telepathischer Schwarm',
    'Warp-Skorpion',
    'Naniten-Phönix',
    'Orbital-Basilisk',
    'Cyber-Bestie',
    'Nullpunkt-Wolf',
    'Schwerkraft-Krake',
    'Daten-Geisttier',
    'Schildgenerator-Bär',
    'Laseraugen-Luchs',
    'Klon-Chimäre',
    'Arkane Servo-Kreatur',
  ],

  MUTANT_MITTELALTER: [
    'Zweiköpfiger Wolf',
    'Riesenratte',
    'Hornhäutiger Bär',
    'Leuchtender Fischotter',
    'Knochenplatten-Eber',
    'Säure speiende Kröte',
    'Übergroße Spinne',
    'Flügeltragender Hirsch',
    'Brandnarben-Fuchs',
    'Dreifachkiefer-Hund',
    'Pestkryptide',
    'Runenverätztes Tier',
    'Sumpfleviathan (jung)',
    'Augenhäufchen-Schlange',
    'Klauenüberwuchs-Wiesel',
    'Hornlose Bestie',
    'Fleischhaufen-Wildschwein',
    'Parasitärer Wolf',
    'Verwachsener Adler',
    'Schattenverfärbter Luchs',
  ],
  MUTANT_GEGENWART: [
    'Chemikalien-Alligator',
    'Kernkraft-Fisch',
    'Dreiäugige Katze',
    'Asbestlunge-Bär',
    'Ölteppich-Krabbe',
    'Mikroplastik-Vogel',
    'Schwermetall-Frosch',
    'Klonierter Hybridhund',
    'Laborflucht-Chimäre',
    'Übergröße-Stadttaube',
    'Giftgrün leuchtender Waschbär',
    'Zweischwänziger Marder',
    'Tumorlastiger Hirsch',
    'Kontaminierter Kojote',
    'Genfehler-Wolf',
    'Strandungs-Krake',
    'Fabrikabfluss-Biest',
    'Krebszellen-Schlange',
    'Strahlungsfuchs',
    'Biohazard-Nagetier',
  ],
  MUTANT_ZUKUNFT: [
    'Reaktor-Kernbestie',
    'Gen-Stack-Überlauf',
    'Kollapsfeld-Ratte',
    'Strahlungsadapt-Wurm',
    'Fehlklon: Vielbeiner',
    'Ökosystem-Kollaps-Hybrid',
    'Naniten-Mutation',
    'Terraform-Fehler-Bär',
    'Kryo-Leck-Amphibie',
    'Schwerkraft-Deformation',
    'Psi-Riss-Tier',
    'Schrottplatz-Chimäre',
    'Ödland-Überlebenskäfer',
    'Säurenebel-Skorpion',
    'Doppelherz-Panther',
    'Panzerhaut-Wolf',
    'Optik-Störspinne',
    'Servo-Wucherungen',
    'Klon-Kaskade',
    'Artefakt-infiziertes Reptil',
  ],

  MONSTER_MITTELALTER: [
    'Troll',
    'Oger',
    'Riese',
    'Ghul',
    'Wiedergänger',
    'Wasserscheuch',
    'Lindwurm',
    'Riesenschlange',
    'Blutegelkönig',
    'Knochengolem',
    'Dämonenhund',
    'Nachtmahr',
    'Seelenfresser',
    'Schrottgolem',
    'Morastbestie',
    'Höllenhund',
    'Gargoyle',
    'Untoter Ritter',
    'Schattenbestie',
    'Schlund des Abgrunds',
  ],
  MONSTER_GEGENWART: [
    'Urban Legend: Hunde-Biest',
    'Kult-Summoning',
    'Serial-Killer-Geist',
    'Massengrab-Wandler',
    'U-Bahn-Tentakelmonster',
    'Ketzerischer Golem',
    'Internet-Creepypasta-Wesen',
    'Okkultes Portalwesen',
    'Blutritual-Monstrum',
    'Industrieunfall-Dämon',
    'Katakomben-Lindwurm',
    'Poltergeist-Schwarm',
    'Pestdämon',
    'Amoklaufender Konstrukt',
    'Schatten aus dem Fernseher',
    'Körperfresser',
    'Nachtalbtraum',
    'Höllenportalbrut',
    'Leichenberg-Zombie',
    'Verfluchtes Maskenwesen',
  ],
  MONSTER_ZUKUNFT: [
    'Singularitäts-Schlund',
    'Blackout-Dämon',
    'KI-Übernahme-Biest',
    'Warp-Scheusal',
    'Nullzonen-Titan',
    'Hivemind-Parasit',
    'Orbital-Waffe (beseelt)',
    'Grey-Goo-Bestie',
    'Psi-Horror',
    'Dimensionsschnittler',
    'Reaktor-Kerngeist',
    'Naniten-Schwarmmonster',
    'Schrottplanet-Leviathan',
    'Event-Horizont-Wurm',
    'Kollapsfeld-Phantom',
    'Labor-Gott-Fragment',
    'Bioforge-Abscheu',
    'Todessatellit (inkarniert)',
    'Arkane Firewall-Bestie',
    'Posthumaner Alptraum',
  ],

  LEBENSRAUM_MITTELALTER: [
    'Dichte Wälder und Bachläufe',
    'Nebelmoore und Torfstiche',
    'Hochgebirgspässe und Felsspalten',
    'Verfallene Burgruinen',
    'Dunkle Höhlensysteme',
    'Flussauen und Schilfgebiete',
    'Brachland an Handelswegen',
    'Heilige Haine und Steinkreise',
    'Küstenklippen und Gezeitenpools',
    'Steppenrand und Salzpfannen',
  ],
  LEBENSRAUM_GEGENWART: [
    'Stadtrand, Industriegebiete und Deponien',
    'U-Bahntunnel und Kanalisation',
    'Alte Militäranlagen',
    'Nationalparks und Schutzgebiete',
    'Häfen, Molen und Wracks',
    'Ehemalige Fabrikareale',
    'Windparks und Hochspannungstrassen',
    'Flussdelta und Auwaldreste',
    'Randlage von Megacity-Slum',
    'Stillgelegte Tagebau-Seen',
  ],
  LEBENSRAUM_ZUKUNFT: [
    'Terraform-Kuppeln und Agroröhren',
    'Ödland zwischen Habitationskuppeln',
    'Orbitale und Dockanlagen',
    'Unterirdische Kühlstollen',
    'Versiegelte Arkologie-Ebenen',
    'Schrottfelder und Recycler-Zonen',
    'Kontaminierte Sektoren ohne Luftfilter',
    'Ley-/Daten-Knotenpunkte',
    'Kryo-Lager und Eiswüsten',
    'Toxische Ozeane und Treibgutinseln',
  ],

  STAERKEN: [
    'Schneller Nahkampf',
    'Harter Panzer / dicke Haut',
    'Gift oder Betäubung',
    'Packtaktik im Rudel',
    'Blendende Geschwindigkeit',
    'Kamouflage / Tarnung',
    'Regeneration',
    'Übernatürliche Widerstandskraft',
    'Reichweite / Sprungangriff',
    'Erschreckender Schrei',
    'Magische Aura',
    'Höhenvorteil (Flug, Klettern)',
    'Graben / Untergrund',
    'Hinterhalt-Instinkt',
    'Starker Biss / Zermalmen',
  ],
  SCHWAECHEN: [
    'Laut und schwer zu übersehen',
    'Empfindliche Sinne (Licht, Lärm)',
    'Territorial und vorhersehbar',
    'Schwacher Fernkampf',
    'Hitze- oder Kälteanfälligkeit',
    'Abhängigkeit von Rudelführung',
    'Heilige Symbole / Weihrauch',
    'Silber, Eisen oder Salz',
    'Lange Erholung nach Anstrengung',
    'Angst vor Feuer',
    'Schwere bei nassem Terrain',
    'Magische Bindungen möglich',
    'Schlaf- oder Winterschlaf-Zyklen',
    'Junge / brutpflegende Phase',
    'Verletzliche Augen oder Weichteile',
  ],
};
