/**
 * Wortlisten für den Fraktions-Zufallsgenerator (epochenabhängige Namen).
 */
window.HTBAH = window.HTBAH || {};

window.HTBAH.ZufallsgeneratorFraktionListen = {
  ARTEN: [
    'Partei',
    'Gilde',
    'Bande',
    'Lager',
    'Minderheit',
    'Sekte',
    'Kartell',
    'Loge',
    'Bund',
    'Klique',
    'Clan',
    'Haus',
    'Allianz',
    'Genossenschaft',
    'Bruderschaft',
    'Schwesternschaft',
    'Zirkel',
    'Front',
    'Bündnis',
    'Vereinigung',
  ],

  ZIELE: [
    'Macht in der Stadt sichern',
    'ein Gesetz kippen oder durchsetzen',
    'Ressourcen monopolisieren',
    'Glaubensgemeinschaft ausweiten',
    'Rache an einer Rivalengruppe',
    'Flucht oder Asyl für Angehörige',
    'kulturelle Anerkennung erzwingen',
    'ein Artefakt oder Wissen bergen',
    'die Herrschaft einer Person stürzen',
    'Handelsrouten kontrollieren',
    'ein Territorium unabhängig machen',
    'korrupte Würdenträger bloßstellen',
    'ein Gerücht in die Welt setzen',
    'ein Bündnis mit Außenstehenden erzwingen',
    'Tradition gegen Reform durchsetzen',
  ],

  GESINNUNG_VERHALTEN: [
    'rechtschaffen, offiziell kooperativ, hinter den Kulissen hart',
    'chaotisch, impulsiv, aber gegenüber Mitgliedern loyal',
    'neutral, verhandlungsbereit, opportunistisch',
    'böswillig, erpresserisch, mit faustdicker Freundlichkeit',
    'idealistisch, unbequem für Autoritäten, manchmal naiv',
    'paranoid, verschwörerisch, schwer zu lesen',
    'pragmatisch, gewaltscheu bis es eng wird',
    'fanatisch, ritualisiert, wenig Kompromiss',
    'korrupt, bestechlich, dabei „regelbasiert“',
    'solidarisch nach innen, aggressiv nach außen',
    'elitär, exklusiv, mit strenger Aufnahmeprüfung',
    'populistisch, laut, emotional aufgeladen',
  ],

  /** Mittelalter: Namensbausteine */
  MITTEL_ADJ: [
    'Schwarze',
    'Rote',
    'Goldene',
    'Eiserne',
    'Stille',
    'Weiße',
    'Grüne',
    'Heilige',
    'Verbotene',
    'Alte',
    'Neue',
    'Freie',
    'Letzte',
    'Dunkle',
  ],
  MITTEL_SUB: [
    'Fähnlein',
    'Lanze',
    'Krone',
    'Rose',
    'Eiche',
    'Säule',
    'Flamme',
    'Schild',
    'Glocke',
    'Brücke',
    'Schar',
    'Sippe',
    'Runen',
    'Federn',
  ],
  MITTEL_ORG: [
    'Bruderschaft',
    'Zunft',
    'Orden',
    'Gilde',
    'Rat',
    'Banner',
    'Lade',
    'Hof',
    'Komturei',
  ],

  /** Gegenwart */
  GEO_MODERN: [
    'Nord',
    'Süd',
    'Rhein',
    'Hafen',
    'Mitte',
    'Altstadt',
    'Ring',
    'Kiez',
    'Tal',
    'See',
  ],
  MODERN_SUFFIX: [
    'Forum',
    'Netzwerk',
    'Initiative',
    'Bündnis',
    'Allianz',
    'Plattform',
    'Aktionskreis',
    'Kooperative',
    'Vereinigung',
    'Bürgerliste',
  ],

  /** Zukunft */
  SF_PREFIX: [
    'Sektor',
    'Node',
    'Orbital',
    'Raster',
    'Kern',
    'Echo',
    'Flux',
    'Neuro',
    'Synth',
    'Void',
  ],
  SF_CORE: [
    'Syndikat',
    'Kollektiv',
    'Kadenz',
    'Pakt',
    'Cluster',
    'Enklave',
    'Array',
    'Covenant',
    'Vector',
    'Nexus',
  ],
  SF_NUM: ['7', '12', '0', 'Ω', 'IX', '3', 'Prime', 'Null'],

  OEFFENTLICHES_BILD: [
    'wird als unnahbar beschrieben',
    'gilt als „praktisch“ und lästig für Behörden',
    'hat Sympathien in der Bevölkerung',
    'wird gefürchtet, aber kaum verstanden',
    'tritt als Wohltäter auf, Hintergrund unklar',
    'ist in Gerüchten allgegenwärtig',
    'wirkt fromm und harmlos — bis man genauer hinsieht',
    'hat alte Familien hinter sich',
    'wird mit Aberglauben und Legenden überzogen',
    'scheint klein, zieht aber viele Fäden',
  ],

  OEFFENTLICHES_BILD_GEGENWART: [
    'tritt in den Medien als NGO oder Verein auf',
    'wirkt harmlos auf Social Media — offline anders',
    'hat Lobbykontakte in der Verwaltung',
    'wird mit Verschwörungstheorien überzogen',
    'sponsert lokale Events und kauft sich Sympathie',
    'gilt als „zu modern“ für die Altstadt',
    'steht unter Beobachtung der Finanzbehörden',
    'wirkt wie ein Startup, handelt wie ein Kartell',
    'ist in Gerichtsakten nur am Rand erwähnt',
    'hat eine glänzende Website und wenig Transparenz',
  ],

  OEFFENTLICHES_BILD_ZUKUNFT: [
    'ist offiziell eine autonome Verwaltungseinheit',
    'wird von KI-Analysten als Risikofaktor eingestuft',
    'tritt als Schutzgilde für Kolonisten auf',
    'operiert im Schatten orbitaler Verträge',
    'wirkt wie ein Kult — nennt sich „Syndikat“',
    'hat Zugang zu militärischen Relaisstationen',
    'ist in alten Archiven nur als Codezeile bekannt',
    'kontrolliert Handelsrouten zwischen Sektoren',
    'wird von Pilgern und Händlern gleichermaßen gefürchtet',
    'scheint demokratisch — Entscheidungen fallen anderswo',
  ],

  INTERNE_DYNAMIK: [
    'Führungsstreit zwischen Alten und Jungen',
    'Spitzelverdacht lastet auf mehreren Mitgliedern',
    'starker Mentor-Kult um eine Figur',
    'Rituale halten die Gruppe zusammen',
    'knappes Budget zwingt zu riskanten Jobs',
    'Blutfehde mit einer rivalisierenden Sippe',
    'Geheimbund innerhalb des Bundes',
    'neue Mitglieder müssen eine Prüfung bestehen',
    'Informanten der Krone sind im Rat vermutet',
    'ein Erbe und ein Bastard streiten um die Führung',
  ],

  INTERNE_DYNAMIK_GEGENWART: [
    'Generationskonflikt zwischen Gründern und Neuen',
    'interner Chat leakt regelmäßig nach außen',
    'Whistleblower drohen mit Enthüllung',
    'Finanzierung aus dubiosen Quellen',
    'Führungskrise nach einem Skandal',
    'ideologische Spaltung in zwei Lager',
    'ein Mitglied arbeitet offenbar für die Polizei',
    'Burnout und Fluktuation in der Basis',
    'Streit um Markenrechte und Namen',
    'geheime Abstimmungen ohne Protokoll',
  ],

  INTERNE_DYNAMIK_ZUKUNFT: [
    'KI-Abstimmung vs. menschlicher Rat — permanenter Konflikt',
    'Saboteure aus einem rivalisierenden Sektor',
    'Klon-Linie und Original streiten um Autorität',
    'Ressourcenknappheit nach Frachterverlust',
    'Geheime Abkommen mit Schmugglerclans',
    'Fanatiker wollen „reine“ Mitgliedschaft',
    'Datenarchiv wurde manipuliert — niemand gesteht',
    'Schwarzmarkt-Deals finanzieren den Alltag',
    'ein Prophet und ein Technokrat teilen die Macht',
    'Verrat durch einen eingeschleusten Agenten',
  ],

  ATMOSPHAERE: [
    'Treffen finden oft bei Kerzenlicht und Flüstern statt.',
    'Das Wappen ist überall — selbst auf Bierkrügen.',
    'Mitglieder erkennen sich an einem diskreten Zeichen am Gürtel.',
    'Gerüchte über Rituale in Kellern halten die Stadt in Atem.',
    'Alte Chroniken im Archiv erzählen von glorreichen Tagen.',
    'Neulinge werden zuerst misstrauisch beäugt.',
    'Die Führung spricht selten öffentlich — Botschaften laufen über Boten.',
    'Ein Lied der Gruppe wird in Tavernen heimlich gesungen.',
    'Spenden und Schutzgeld verschwimmen in der Praxis.',
    'Die Fraktion wirkt klein — bis man ihre Netzwerke sieht.',
  ],

  ATMOSPHAERE_GEGENWART: [
    'Vereinssitzungen laufen über Videocall und Präsenz gleichzeitig.',
    'Sticker und Hashtags prägen das öffentliche Bild.',
    'Mitglieder treffen sich in einem Hinterzimmer eines Cafés.',
    'Flyer und Petitionen sind schneller als Gerüchte.',
    'Die Satzung ist online — die wahren Regeln nicht.',
    'Spendenquittungen und Schattenkonten existieren parallel.',
    'Pressemitteilungen klingen harmlos, Aktionen weniger.',
    'Ein Discord-Server hält die Basis mobilisiert.',
    'Lokale Politiker nicken — und schweigen.',
    'Die Fraktion wirkt modern — die Methoden sind es nicht immer.',
  ],

  ATMOSPHAERE_ZUKUNFT: [
    'Verschlüsselte Kanäle flackern auf Holodisplays.',
    'Mitglieder tragen identische Implantat-Codes — unsichtbar für Außenstehende.',
    'Treffen in Druckkammern oder Null-g-Zonen sind normal.',
    'Das Symbol der Gruppe leuchtet auf Kuppeln bei Nacht.',
    'Rituale mischen Archaik und Hightech.',
    'Neulinge werden per Gen-Scan geprüft.',
    'Die Fraktion kontrolliert einen Luftschleusen-Zugang.',
    'Gerüchte über KI-Orakel in der Führungsebene.',
    'Schwarze Marktdaten und offizielle Logs widersprechen sich.',
    'Von außen wirkt sie wie ein Verwaltungsbüro — innen wie ein Tempel.',
  ],
};
