/**
 * Wortlisten für den Fraktions-Zufallsgenerator (epochenabhängige Namen).
 */
window.HTBAH = window.HTBAH || {};

window.HTBAH.ZufallsgeneratorFraktionListen = {
  ARTEN: [
    'Partei',
    'Gilde',
    'Bande',
    'Lager',
    'Minderheit',
    'Sekte',
    'Kartell',
    'Loge',
    'Bund',
    'Klique',
    'Clan',
    'Haus',
    'Allianz',
    'Genossenschaft',
    'Bruderschaft',
    'Schwesternschaft',
    'Zirkel',
    'Front',
    'Bündnis',
    'Vereinigung',
  ],

  ZIELE: [
    'Macht in der Stadt sichern',
    'ein Gesetz kippen oder durchsetzen',
    'Ressourcen monopolisieren',
    'Glaubensgemeinschaft ausweiten',
    'Rache an einer Rivalengruppe',
    'Flucht oder Asyl für Angehörige',
    'kulturelle Anerkennung erzwingen',
    'ein Artefakt oder Wissen bergen',
    'die Herrschaft einer Person stürzen',
    'Handelsrouten kontrollieren',
    'ein Territorium unabhängig machen',
    'korrupte Würdenträger bloßstellen',
    'ein Gerücht in die Welt setzen',
    'ein Bündnis mit Außenstehenden erzwingen',
    'Tradition gegen Reform durchsetzen',
  ],

  GESINNUNG_VERHALTEN: [
    'rechtschaffen, offiziell kooperativ, hinter den Kulissen hart',
    'chaotisch, impulsiv, aber gegenüber Mitgliedern loyal',
    'neutral, verhandlungsbereit, opportunistisch',
    'böswillig, erpresserisch, mit faustdicker Freundlichkeit',
    'idealistisch, unbequem für Autoritäten, manchmal naiv',
    'paranoid, verschwörerisch, schwer zu lesen',
    'pragmatisch, gewaltscheu bis es eng wird',
    'fanatisch, ritualisiert, wenig Kompromiss',
    'korrupt, bestechlich, dabei „regelbasiert“',
    'solidarisch nach innen, aggressiv nach außen',
    'elitär, exklusiv, mit strenger Aufnahmeprüfung',
    'populistisch, laut, emotional aufgeladen',
  ],

  /** Mittelalter: Namensbausteine */
  MITTEL_ADJ: [
    'Schwarze',
    'Rote',
    'Goldene',
    'Eiserne',
    'Stille',
    'Weiße',
    'Grüne',
    'Heilige',
    'Verbotene',
    'Alte',
    'Neue',
    'Freie',
    'Letzte',
    'Dunkle',
  ],
  MITTEL_SUB: [
    'Fähnlein',
    'Lanze',
    'Krone',
    'Rose',
    'Eiche',
    'Säule',
    'Flamme',
    'Schild',
    'Glocke',
    'Brücke',
    'Schar',
    'Sippe',
    'Runen',
    'Federn',
  ],
  MITTEL_ORG: [
    'Bruderschaft',
    'Zunft',
    'Orden',
    'Gilde',
    'Rat',
    'Banner',
    'Lade',
    'Hof',
    'Komturei',
  ],

  /** Gegenwart */
  GEO_MODERN: [
    'Nord',
    'Süd',
    'Rhein',
    'Hafen',
    'Mitte',
    'Altstadt',
    'Ring',
    'Kiez',
    'Tal',
    'See',
  ],
  MODERN_SUFFIX: [
    'Forum',
    'Netzwerk',
    'Initiative',
    'Bündnis',
    'Allianz',
    'Plattform',
    'Aktionskreis',
    'Kooperative',
    'Vereinigung',
    'Bürgerliste',
  ],

  /** Zukunft */
  SF_PREFIX: [
    'Sektor',
    'Node',
    'Orbital',
    'Raster',
    'Kern',
    'Echo',
    'Flux',
    'Neuro',
    'Synth',
    'Void',
  ],
  SF_CORE: [
    'Syndikat',
    'Kollektiv',
    'Kadenz',
    'Pakt',
    'Cluster',
    'Enklave',
    'Array',
    'Covenant',
    'Vector',
    'Nexus',
  ],
  SF_NUM: ['7', '12', '0', 'Ω', 'IX', '3', 'Prime', 'Null'],
};
