/**
 * Wortlisten & Gewichte für das Gegenstand-Modul (Waffen, Kleidung, Sonstiges).
 */
window.HTBAH = window.HTBAH || {};

window.HTBAH.ZufallsgeneratorGegenstandListen = {
  WAFFE_MITTELALTER: [
    { wert: 'Schwert', gewicht: 14 },
    { wert: 'Langschwert', gewicht: 10 },
    { wert: 'Kurzschwert', gewicht: 10 },
    { wert: 'Zweihänder', gewicht: 6 },
    { wert: 'Streitaxt', gewicht: 11 },
    { wert: 'Kriegsbeil', gewicht: 7 },
    { wert: 'Streitkolben', gewicht: 9 },
    { wert: 'Morgenstern', gewicht: 5 },
    { wert: 'Dolch', gewicht: 12 },
    { wert: 'Stilett', gewicht: 6 },
    { wert: 'Bogen', gewicht: 8 },
    { wert: 'Langbogen', gewicht: 5 },
    { wert: 'Armbrust', gewicht: 6 },
    { wert: 'Speer', gewicht: 10 },
    { wert: 'Hellebarde', gewicht: 7 },
    { wert: 'Glefe', gewicht: 5 },
    { wert: 'Kriegshammer', gewicht: 6 },
    { wert: 'Peitsche', gewicht: 4 },
    { wert: 'Wurfbeil', gewicht: 5 },
    { wert: 'Schild (nagelbeschlagen)', gewicht: 4 },
  ],

  WAFFE_GEGENWART: [
    { wert: 'Pistole', gewicht: 20 },
    { wert: 'Revolver', gewicht: 12 },
    { wert: 'Sturmgewehr', gewicht: 13 },
    { wert: 'Maschinenpistole', gewicht: 8 },
    { wert: 'Jagdgewehr', gewicht: 7 },
    { wert: 'Scharfschützengewehr', gewicht: 5 },
    { wert: 'Schrotflinte', gewicht: 8 },
    { wert: 'Messer', gewicht: 14 },
    { wert: 'Kampfmesser', gewicht: 9 },
    { wert: 'Machete', gewicht: 6 },
    { wert: 'Schwert (Trainingswaffe)', gewicht: 2 },
    { wert: 'Axt (Beil)', gewicht: 2 },
    { wert: 'Baseballschläger', gewicht: 4 },
    { wert: 'Elektroschocker', gewicht: 5 },
    { wert: 'Pfefferspray', gewicht: 4 },
    { wert: 'Compoundbogen', gewicht: 3 },
  ],

  WAFFE_ZUKUNFT: [
    { wert: 'Phaser', gewicht: 14 },
    { wert: 'Strahlenpistole', gewicht: 12 },
    { wert: 'Plasmagewehr', gewicht: 11 },
    { wert: 'Impulsgewehr', gewicht: 9 },
    { wert: 'Laserkarabiner', gewicht: 11 },
    { wert: 'Railgun (Leicht)', gewicht: 6 },
    { wert: 'Molekulardolch', gewicht: 7 },
    { wert: 'Energieklinge', gewicht: 6 },
    { wert: 'Gravitationspeitsche', gewicht: 5 },
    { wert: 'Sturmgewehr (Slum-Modifikation)', gewicht: 5 },
    { wert: 'Pistole (veraltet)', gewicht: 4 },
    { wert: 'Kurzschwert (Antiquität)', gewicht: 2 },
    { wert: 'Streitaxt (Sammlerstück)', gewicht: 2 },
    { wert: 'Quantenpeitsche', gewicht: 7 },
    { wert: 'Ionenkanone (tragbar)', gewicht: 4 },
    { wert: 'Akustikwaffe', gewicht: 3 },
    { wert: 'Nanitenklinge', gewicht: 5 },
  ],

  KLEIDUNG_MITTELALTER: [
    'Wollumhang',
    'gepolstertes Wams',
    'Ledermantel',
    'Leinenhemd',
    'Wollkleid',
    'Kutte',
    'Reiterstiefel mit Gamaschen',
    'Kettenhemd (unter Stoff)',
    'Brünne',
    'Hose mit Schnürung',
    'Kapuzenumhang',
    'Fellfutter',
    'Samtkappe',
    'Gürtel mit Messingplatten',
    'Strickweste',
    'Lederhut mit breiter Krempe',
    'Wollstrümpfe',
    'Trachtenrock (schwer)',
    'Mönchskutte',
    'Jägerweste mit Taschen',
  ],

  KLEIDUNG_GEGENWART: [
    'Jeans und Hoodie',
    'Anzug mit Mantel',
    'Regenjacke und Rucksack',
    'Lederjacke',
    'Trainingsanzug',
    'Kittel',
    'Dirndl (modern interpretiert)',
    'Parka und Wanderschuhe',
    'Businesshemd und Krawatte',
    'Cargo-Hose und Arbeitsstiefel',
    'Leggings und Oversize-Pullover',
    'Sicherheitsweste',
    'Kochjacke',
    'Pilotenjacke',
    'Sonnenhut und Leinenhemd',
    'Neoprenanzug (kurz)',
    'Schutzbrille und Overall',
    'Trenchcoat',
    'Sneaker und Windbreaker',
    'Arbeitslatzhose',
  ],

  KLEIDUNG_ZUKUNFT: [
    'Kampfanzug mit Kühlkreislauf',
    'Overall mit HUD-Streifen',
    'Hologramm-Umhang',
    'Schwerelos-Overall',
    'Panzerhemd (flexibel)',
    'Schutzanzug gegen Vakuum',
    'Alltagsrobe mit Nanofaser',
    'Kühlpanzerung (unter Stoff)',
    'Kletteranzug mit Mikrohaken',
    'Tarnumhang (aktiv)',
    'Schwerkraftstiefel',
    'Medizin-Exo (leicht)',
    'Künstliche Haut (optisch)',
    'Datenschleier (Schal)',
    'Atemmaske mit Filter',
    'Leitfähige Handschuhe',
    'Unterdruck-Kapuze',
    'Servo-Ärmel',
    'Bio-Seidenhemd',
  ],

  SONSTIGES_MITTELALTER: [
    'Eiserne Laterne',
    'Bronzener Kompass',
    'Wachszylinder mit Siegel',
    'Silberner Schlüsselbund',
    'Lederkarte',
    'Silberlöffel',
    'Hornbecher',
    'Runenstein',
    'Heiligenbild',
    'Salzfass',
    'Kerzenhalter',
    'Schreibfeder und Röhre',
    'Würfel aus Knochen',
    'Amulett aus Bernstein',
    'Kleiner Spiegel',
    'Flöte aus Holz',
    'Kleine Truhe',
    'Federkiel',
    'Siegelring',
    'Trankfläschchen (leer)',
  ],

  SONSTIGES_GEGENWART: [
    'Smartphone (abgeschlagen)',
    'Taschenlampe',
    'Feuerzeug',
    'Fernglas',
    'USB-Stick mit Aufkleber',
    'Multitool',
    'Kopfhörer',
    'Powerbank',
    'Fahrscheinmappe',
    'Schweißgerät (klein)',
    'Digitalkamera',
    'Schlüsselanhänger mit Chip',
    'Notizblock',
    'Taschenmesser (legal)',
    'Feuerlöscher (Mini)',
    'GPS-Empfänger',
    'Kabelrolle',
    'Medikamentendose',
  ],

  SONSTIGES_ZUKUNFT: [
    'Datenkristall',
    'Hover-Toolkit',
    'Energiezelle (Standard)',
    'Universal-Öffner',
    'Holo-Notizblock',
    'Quantenverschlüsselungschip',
    'Mini-Drohne (defekt)',
    'Med-Naniten-Spritze',
    'Übersetzungs-Ohrstecker',
    'Kraftfeld-Projektor (Mini)',
    'Persönlicher Schild (Einweg)',
    'Bio-Monitor',
    'Teleport-Notfallbake',
    'Gedächtnis-Stick',
    'Gravitationsanker',
  ],

  MATERIAL: [
    'Stahl',
    'Holz',
    'Leder',
    'Bronze',
    'Eisen',
    'Silber',
    'Kristall',
    'Kunststoff',
    'Legierung',
    'Titan',
    'Keramik',
    'Obsidian',
    'Knochen',
    'Messing',
    'Kupfer',
    'Carbon',
    'Glas',
    'Seide',
    'Wolle',
    'Vollholz',
  ],

  ZUSTAND_ITEM: [
    'gebraucht',
    'neuwertig',
    'ramponiert',
    'kunstvoll verziert',
    'schlicht',
    'modifiziert',
    'stark abgenutzt',
    'minimal gebraucht',
    'mit Initialen',
    'mit kleiner Delle',
    'ölverschmiert',
    'staubig',
    'poliert',
  ],

  FARBE: [
    'dunkel',
    'hell',
    'grau',
    'grünlich',
    'rostrot',
    'silbern',
    'matt schwarz',
    'kupferfarben',
    'bläulich',
    'bernstein',
    'violett schimmernd',
    'tarnfarben',
    'perlfarben',
  ],

  FLAVOR: [
    'Wirkt leicht überraschend schwer.',
    'Hat eine kleine Gravur.',
    'Riecht nach Öl und Staub.',
    'Vibriert kaum merklich in der Hand.',
    'Ein Etikett ist kaum lesbar.',
    'Kühlt die Finger leicht.',
    'Summt bei Berührung.',
    'Zieht kleine Faserfäden an.',
    'Reflektiert Licht ungewöhnlich.',
    'Fühlt sich warm an.',
    'Hat eine unsichtbare Naht.',
    'Klingt bei leichtem Stoß hohl.',
    'Riecht nach Ozon.',
    'Wirkt älter, als es ist.',
  ],
};
