/**
 * Wortlisten für das NPC-Modul.
 */
window.HTBAH = window.HTBAH || {};

window.HTBAH.ZufallsgeneratorNpcListen = {
  VORNAMEN_M: [
    'Jonas',
    'Lukas',
    'Felix',
    'Tobias',
    'Matthias',
    'Simon',
    'Daniel',
    'Stefan',
    'Markus',
    'Christian',
    'Andreas',
    'Thomas',
    'Michael',
    'Sebastian',
    'Florian',
    'Alexander',
    'Benjamin',
    'Christoph',
    'David',
    'Dominik',
    'Erik',
    'Fabian',
    'Georg',
    'Henrik',
    'Jan',
    'Johannes',
    'Julian',
    'Kevin',
    'Leon',
    'Martin',
    'Maximilian',
    'Niklas',
    'Oliver',
    'Patrick',
    'Paul',
    'Philipp',
    'Raphael',
    'Robert',
    'Samuel',
    'Tim',
    'Vincent',
    'Wolfgang',
    'Adrian',
    'Benedikt',
    'Cornelius',
    'Emil',
    'Finn',
    'Gabriel',
    'Hannes',
    'Ignaz',
    'Jakob',
    'Karl',
    'Lorenz',
    'Moritz',
    'Noah',
    'Oscar',
    'Peter',
    'Quirin',
    'Richard',
    'Sören',
  ],

  VORNAMEN_W: [
    'Anna',
    'Laura',
    'Julia',
    'Sarah',
    'Lisa',
    'Katharina',
    'Maria',
    'Sophie',
    'Emma',
    'Hannah',
    'Lea',
    'Nina',
    'Clara',
    'Helena',
    'Theresa',
    'Amelie',
    'Bettina',
    'Charlotte',
    'Diana',
    'Elisa',
    'Franziska',
    'Greta',
    'Hedwig',
    'Ines',
    'Johanna',
    'Karoline',
    'Luisa',
    'Magdalena',
    'Nora',
    'Olivia',
    'Petra',
    'Rebecca',
    'Sabine',
    'Tabea',
    'Ulrike',
    'Valentina',
    'Wanda',
    'Yvonne',
    'Zoe',
    'Agnes',
    'Brigitte',
    'Christina',
    'Dorothea',
    'Elena',
    'Fiona',
    'Gisela',
    'Hilda',
    'Iris',
    'Jasmin',
    'Klara',
    'Lina',
    'Miriam',
    'Nadine',
    'Paula',
    'Ruth',
    'Stella',
    'Thea',
    'Ute',
    'Vera',
    'Wilma',
  ],

  NACHNAMEN: [
    'Müller',
    'Schmidt',
    'Schneider',
    'Fischer',
    'Weber',
    'Meyer',
    'Wagner',
    'Becker',
    'Schulz',
    'Hoffmann',
    'Koch',
    'Bauer',
    'Richter',
    'Klein',
    'Wolf',
    'Schröder',
    'Neumann',
    'Schwarz',
    'Zimmermann',
    'Braun',
    'Krüger',
    'Hartmann',
    'Lange',
    'Werner',
    'Krause',
    'Meier',
    'Lehmann',
    'Huber',
    'Kaiser',
    'Fuchs',
    'Peters',
    'Lang',
    'Weiß',
    'Jung',
    'Hahn',
    'Schubert',
    'Vogel',
    'Friedrich',
    'Günther',
    'Keller',
    'Graf',
    'Berger',
    'Sommer',
    'Busch',
    'Seidel',
    'Lorenz',
    'Baumann',
    'Frank',
    'Simon',
    'Albrecht',
    'Winkler',
    'Brunner',
    'Böhm',
    'Winter',
    'Kraus',
    'Martin',
    'Schumacher',
    'Krämer',
    'Vogt',
    'Stein',
    'Jäger',
    'Otto',
    'Groß',
    'Heinrich',
    'Brandt',
    'Haas',
    'Schuster',
    'Schreiber',
    'Ewald',
    'Dietrich',
    'Roth',
    'Neubert',
    'Blum',
    'Schwarzer',
    'Ziegler',
    'Kuhn',
    'Kühn',
    'Pohl',
    'Korn',
    'Bergmann',
    'Sauer',
    'Engel',
    'Horn',
    'Busse',
    'Ackermann',
  ],

  SPITZNAMEN: [
    'Fuchs',
    'Bär',
    'Eule',
    'Rabe',
    'Wolf',
    'Elch',
    'Dachs',
    'Hase',
    'Krähe',
    'Schild',
    'Hammer',
    'Nadel',
    'Funke',
    'Wind',
    'Staub',
    'Eiche',
    'Stein',
    'Flamme',
    'Nebel',
    'Sturm',
    'Falke',
    'Luchs',
    'Otter',
    'Biber',
    'Hirsch',
    'Uhu',
    'Panther',
    'Krebs',
    'Aal',
    'Barsch',
    'Greif',
    'Drache',
    'Ritter',
    'Pfote',
    'Klaue',
    'Schnabel',
    'Schwan',
    'Taube',
    'Lerche',
    'Star',
    'Marder',
    'Wiesel',
    'Iltis',
  ],

  FAMILIENSTAND: [
    'Ledig',
    'Verheiratet',
    'Verwitwet',
    'Geschieden',
    'Verlobt',
    'Kompliziert',
    'Getrennt lebend',
    'Eingetragene Partnerschaft',
  ],

  STATUR: [
    'Schlank',
    'Kräftig',
    'Klein',
    'Groß',
    'Stämmig',
    'Dünn',
    'Athletisch',
    'Untersetzt',
    'Hager',
    'Breitschultrig',
    'Zierlich',
    'Schwerfällig',
  ],

  GESINNUNG: [
    'Rechtschaffend gut',
    'Neutral gut',
    'Chaotisch gut',
    'Rechtschaffen neutral',
    'Neutral',
    'Chaotisch neutral',
    'Rechtschaffen böse',
    'Neutral böse',
    'Chaotisch böse',
  ],

  BERUF: [
    'Schmied',
    'Händler',
    'Wache',
    'Priester',
    'Gelehrter',
    'Dieb',
    'Bauer',
    'Seemann',
    'Alchemist',
    'Barde',
    'Jäger',
    'Heiler',
    'Schreiber',
    'Gastwirt',
    'Fischer',
    'Gerber',
    'Töpfer',
    'Müller',
    'Bäcker',
    'Metzger',
    'Schneider',
    'Maurer',
    'Zimmermann',
    'Botenläufer',
    'Fährmann',
    'Waldhüter',
    'Kartograph',
    'Uhrmacher',
    'Glasmacher',
    'Koch',
    'Kellner',
    'Leibwächter',
    'Fechtlehrer',
    'Kräuterfrau',
    'Scharlatan',
    'Gaukler',
    'Gräber',
    'Steinmetz',
    'Schmuggler',
    'Spion',
    'Bibliothekar',
    'Advokat',
    'Chirurg',
    'Bader',
  ],

  ZIEL: [
    'Ruhe im Alter finden',
    'Ein Vermächtnis hinterlassen',
    'Die eigene Schuld sühnen',
    'Die Familie schützen',
    'Reichtum anhäufen',
    'Gerechtigkeit üben',
    'Ein Geheimnis bewahren',
    'Aus der Heimat fliehen',
    'Anerkennung erringen',
    'Ein Kunstwerk vollenden',
    'Einen alten Eid erfüllen',
    'Rache an einem Rivalen',
    'Ein Kind wiederfinden',
    'Die Wahrheit aufdecken',
    'Ein Handwerk meistern',
    'In einem fremden Land Fuß fassen',
    'Eine Schuld begleichen',
    'Den eigenen Namen reinwaschen',
    'Einen Kult zerschlagen',
    'Ein Relikt bergen',
    'Einen Vertrag brechen',
    'Neue Freunde finden',
    'Die Liebe des Lebens gewinnen',
    'Ein Erbe antreten',
    'Aus der Schattenwirtschaft aussteigen',
    'Ein Tier retten',
    'Einen Mentor übertreffen',
    'Die eigene Vergangenheit vergessen',
    'Ein Lied vollenden',
    'Einen Frieden aushandeln',
  ],

  EINDRUCK: [
    'wirkt freundlich',
    'wirkt mürrisch',
    'wirkt nervös',
    'wirkt selbstsicher',
    'wirkt verschlossen',
    'wirkt neugierig',
    'wirkt müde',
    'wirkt heiter',
    'wirkt distanziert',
    'wirkt aufbrausend',
    'wirkt nachdenklich',
    'wirkt listig',
    'wirkt ehrlich',
    'wirkt verschmitzt',
    'wirkt grob',
    'wirkt fein',
    'wirkt gehetzt',
    'wirkt gelassen',
    'wirkt stolz',
    'wirkt demütig',
    'wirkt geheimnisvoll',
    'wirkt offenherzig',
    'wirkt paranoid',
    'wirkt verträumt',
    'wirkt pragmatisch',
  ],

  MERKMAL: [
    'auffällige Narbe',
    'fehlender Finger',
    'Tätowierung am Hals',
    'silberner Ring',
    'hölzerner Gehstock',
    'leiser Gang',
    'Humpeln',
    'falsches Auge',
    'silberne Haarsträhne',
    'Sommersprossen',
    'Goldzahn',
    'Brandmal am Handgelenk',
    'Amulett unter der Kleidung',
    'Singender Dialekt',
    'Zittern in der Hand',
    'auffällige Stimme',
    'duftet nach Lavendel',
    'trägt immer Handschuhe',
    'humpelnder Gehilfe',
    'Narbe quer über die Wange',
    'leuchtende Augenfarbe',
    'unruhige Hände',
    'pfeift unbewusst Melodien',
    'trägt einen fremdländischen Schmuck',
    'spricht mit leisem Lispeln',
    'hat ein kleines Muttermal',
  ],
};
