/**
 * Wortlisten für das NPC-Modul.
 */
window.HTBAH = window.HTBAH || {};

window.HTBAH.ZufallsgeneratorNpcListen = {
  VORNAMEN_M: [
    'Jonas',
    'Lukas',
    'Felix',
    'Tobias',
    'Matthias',
    'Simon',
    'Daniel',
    'Stefan',
    'Markus',
    'Christian',
    'Andreas',
    'Thomas',
    'Michael',
    'Sebastian',
    'Florian',
    'Alexander',
    'Benjamin',
    'Christoph',
    'David',
    'Dominik',
    'Erik',
    'Fabian',
    'Georg',
    'Henrik',
    'Jan',
    'Johannes',
    'Julian',
    'Kevin',
    'Leon',
    'Martin',
    'Maximilian',
    'Niklas',
    'Oliver',
    'Patrick',
    'Paul',
    'Philipp',
    'Raphael',
    'Robert',
    'Samuel',
    'Tim',
    'Vincent',
    'Wolfgang',
    'Adrian',
    'Benedikt',
    'Cornelius',
    'Emil',
    'Finn',
    'Gabriel',
    'Hannes',
    'Ignaz',
    'Jakob',
    'Karl',
    'Lorenz',
    'Moritz',
    'Noah',
    'Oscar',
    'Peter',
    'Quirin',
    'Richard',
    'Sören',
  ],

  VORNAMEN_W: [
    'Anna',
    'Laura',
    'Julia',
    'Sarah',
    'Lisa',
    'Katharina',
    'Maria',
    'Sophie',
    'Emma',
    'Hannah',
    'Lea',
    'Nina',
    'Clara',
    'Helena',
    'Theresa',
    'Amelie',
    'Bettina',
    'Charlotte',
    'Diana',
    'Elisa',
    'Franziska',
    'Greta',
    'Hedwig',
    'Ines',
    'Johanna',
    'Karoline',
    'Luisa',
    'Magdalena',
    'Nora',
    'Olivia',
    'Petra',
    'Rebecca',
    'Sabine',
    'Tabea',
    'Ulrike',
    'Valentina',
    'Wanda',
    'Yvonne',
    'Zoe',
    'Agnes',
    'Brigitte',
    'Christina',
    'Dorothea',
    'Elena',
    'Fiona',
    'Gisela',
    'Hilda',
    'Iris',
    'Jasmin',
    'Klara',
    'Lina',
    'Miriam',
    'Nadine',
    'Paula',
    'Ruth',
    'Stella',
    'Thea',
    'Ute',
    'Vera',
    'Wilma',
  ],

  NACHNAMEN: [
    'Müller',
    'Schmidt',
    'Schneider',
    'Fischer',
    'Weber',
    'Meyer',
    'Wagner',
    'Becker',
    'Schulz',
    'Hoffmann',
    'Koch',
    'Bauer',
    'Richter',
    'Klein',
    'Wolf',
    'Schröder',
    'Neumann',
    'Schwarz',
    'Zimmermann',
    'Braun',
    'Krüger',
    'Hartmann',
    'Lange',
    'Werner',
    'Krause',
    'Meier',
    'Lehmann',
    'Huber',
    'Kaiser',
    'Fuchs',
    'Peters',
    'Lang',
    'Weiß',
    'Jung',
    'Hahn',
    'Schubert',
    'Vogel',
    'Friedrich',
    'Günther',
    'Keller',
    'Graf',
    'Berger',
    'Sommer',
    'Busch',
    'Seidel',
    'Lorenz',
    'Baumann',
    'Frank',
    'Simon',
    'Albrecht',
    'Winkler',
    'Brunner',
    'Böhm',
    'Winter',
    'Kraus',
    'Martin',
    'Schumacher',
    'Krämer',
    'Vogt',
    'Stein',
    'Jäger',
    'Otto',
    'Groß',
    'Heinrich',
    'Brandt',
    'Haas',
    'Schuster',
    'Schreiber',
    'Ewald',
    'Dietrich',
    'Roth',
    'Neubert',
    'Blum',
    'Schwarzer',
    'Ziegler',
    'Kuhn',
    'Kühn',
    'Pohl',
    'Korn',
    'Bergmann',
    'Sauer',
    'Engel',
    'Horn',
    'Busse',
    'Ackermann',
  ],

  SPITZNAMEN: [
    'Fuchs',
    'Bär',
    'Eule',
    'Rabe',
    'Wolf',
    'Elch',
    'Dachs',
    'Hase',
    'Krähe',
    'Schild',
    'Hammer',
    'Nadel',
    'Funke',
    'Wind',
    'Staub',
    'Eiche',
    'Stein',
    'Flamme',
    'Nebel',
    'Sturm',
    'Falke',
    'Luchs',
    'Otter',
    'Biber',
    'Hirsch',
    'Uhu',
    'Panther',
    'Krebs',
    'Aal',
    'Barsch',
    'Greif',
    'Drache',
    'Ritter',
    'Pfote',
    'Klaue',
    'Schnabel',
    'Schwan',
    'Taube',
    'Lerche',
    'Star',
    'Marder',
    'Wiesel',
    'Iltis',
  ],

  FAMILIENSTAND: [
    'Ledig',
    'Verheiratet',
    'Verwitwet',
    'Geschieden',
    'Verlobt',
    'Kompliziert',
    'Getrennt lebend',
    'Eingetragene Partnerschaft',
  ],

  STATUR: [
    'Schlank',
    'Kräftig',
    'Klein',
    'Groß',
    'Stämmig',
    'Dünn',
    'Athletisch',
    'Untersetzt',
    'Hager',
    'Breitschultrig',
    'Zierlich',
    'Schwerfällig',
  ],

  GESINNUNG: [
    'Rechtschaffend gut',
    'Neutral gut',
    'Chaotisch gut',
    'Rechtschaffen neutral',
    'Neutral',
    'Chaotisch neutral',
    'Rechtschaffen böse',
    'Neutral böse',
    'Chaotisch böse',
  ],

  BERUF_MITTELALTER: [
    'Schmied',
    'Händler',
    'Wache',
    'Priester',
    'Gelehrter',
    'Dieb',
    'Bauer',
    'Seemann',
    'Alchemist',
    'Barde',
    'Jäger',
    'Heiler',
    'Schreiber',
    'Gastwirt',
    'Fischer',
    'Gerber',
    'Töpfer',
    'Müller',
    'Bäcker',
    'Metzger',
    'Schneider',
    'Maurer',
    'Zimmermann',
    'Botenläufer',
    'Fährmann',
    'Waldhüter',
    'Kartograph',
    'Uhrmacher',
    'Glasmacher',
    'Koch',
    'Kellner',
    'Leibwächter',
    'Fechtlehrer',
    'Kräuterfrau',
    'Scharlatan',
    'Gaukler',
    'Gräber',
    'Steinmetz',
    'Schmuggler',
    'Spion',
    'Bibliothekar',
    'Advokat',
    'Chirurg',
    'Bader',
  ],

  BERUF_GEGENWART: [
    'Polizist',
    'Soldat',
    'Sicherheitskraft',
    'Journalistin',
    'Mechaniker',
    'Notfallsanitäter',
    'IT-Administrator',
    'Programmierer',
    'Barkeeper',
    'Taxifahrerin',
    'Detektiv',
    'Anwältin',
    'Buchhalter',
    'Pflegekraft',
    'Handwerker',
    'Scharfschütze',
    'Drohnenpilot',
    'Kurierfahrer',
    'Feuerwehrmann',
    'Funker',
    'Laborantin',
    'Wissenschaftler',
    'Bauleiter',
    'Spediteur',
    'Schmuggler',
    'Unterhändlerin',
    'Bodyguard',
    'Söldner',
    'Influencer',
    'Historiker',
  ],

  BERUF_ZUKUNFT: [
    'Sicherheitsandroide',
    'Sternenpilotin',
    'Terraforming-Techniker',
    'Datenkurier',
    'Synth-Schmied',
    'Bio-Ingenieurin',
    'Konzernsöldner',
    'Stationswache',
    'Nanomediziner',
    'Archivarin',
    'KI-Flüsterer',
    'Quantenanalystin',
    'Cyberspion',
    'Schrotthändler',
    'Luftschleusenwart',
    'Orbit-Kartograph',
    'Kolonieverwalterin',
    'Exo-Ranger',
    'Signaljäger',
    'Maschinenpriesterin',
    'Runen-Hacker',
    'Wellenreiter',
    'Asteroiden-Bergmann',
    'Holo-Künstler',
    'Drohnenhirte',
    'Plasmamechaniker',
  ],

  ZIEL_MITTELALTER: [
    'Ruhe im Alter finden',
    'Ein Vermächtnis hinterlassen',
    'Die eigene Schuld sühnen',
    'Die Familie schützen',
    'Reichtum anhäufen',
    'Gerechtigkeit üben',
    'Ein Geheimnis bewahren',
    'Aus der Heimat fliehen',
    'Anerkennung erringen',
    'Ein Kunstwerk vollenden',
    'Einen alten Eid erfüllen',
    'Rache an einem Rivalen',
    'Ein Kind wiederfinden',
    'Die Wahrheit aufdecken',
    'Ein Handwerk meistern',
    'In einem fremden Land Fuß fassen',
    'Eine Schuld begleichen',
    'Den eigenen Namen reinwaschen',
    'Einen Kult zerschlagen',
    'Ein Relikt bergen',
    'Einen Vertrag brechen',
    'Neue Freunde finden',
    'Die Liebe des Lebens gewinnen',
    'Ein Erbe antreten',
    'Aus der Schattenwirtschaft aussteigen',
    'Ein Tier retten',
    'Einen Mentor übertreffen',
    'Die eigene Vergangenheit vergessen',
    'Ein Lied vollenden',
    'Einen Frieden aushandeln',
  ],

  ZIEL_GEGENWART: [
    'Einen Korruptionsfall öffentlich machen',
    'Eine große Schuld abbezahlen',
    'Mit der Familie neu anfangen',
    'Den eigenen Namen reinwaschen',
    'Ein Unternehmen übernehmen',
    'Eine Entführung aufklären',
    'Einen Whistleblower schützen',
    'Ein gefährliches Netzwerk zerschlagen',
    'Eine Karriere retten',
    'Ein verlorenes Beweisstück finden',
    'Sich aus der Unterwelt lösen',
    'Den perfekten Coup planen',
    'Eine Katastrophe verhindern',
    'Ein Team wieder zusammenführen',
    'Sich an einem Verräter rächen',
    'Jemanden aus einem Konzern befreien',
    'Politischen Einfluss gewinnen',
    'Eine Wahrheit vertuschen',
    'Eine Stadt sicherer machen',
    'Ein Erbe antreten',
  ],

  ZIEL_ZUKUNFT: [
    'Einen Kolonievertrag sichern',
    'Eine KI von ihren Fesseln lösen',
    'Einen Sternenkarten-Fehler vertuschen',
    'Ein abgestürztes Forschungsschiff bergen',
    'Einen Ressourcenkrieg verhindern',
    'Die eigene Bio-Signatur löschen',
    'Eine verbotene Technologie verkaufen',
    'Eine Raumstation sabotieren',
    'Ein Konzerngeheimnis veröffentlichen',
    'Den Heimatsektor zurückgewinnen',
    'Einen Klon retten',
    'Schulden bei einem Syndikat begleichen',
    'Eine Quarantänezone verlassen',
    'Eine fremde Spezies kontaktieren',
    'Eine ausgestorbene Sprache entschlüsseln',
    'Die Kontrolle über ein Wurmloch sichern',
    'Eine Rebellion finanzieren',
    'Den eigenen Schöpfer finden',
  ],

  GEHEIMNIS_MITTELALTER: [
    'hat bei einem Überfall den Täter gedeckt',
    'führt heimlich eine zweite Identität',
    'schreibt verbotene Briefe an eine verbotene Liebe',
    'verwahrt ein gestohlenes Relikt',
    'steht unter dem Schutz eines verbotenen Kults',
    'hat den Tod eines Rivalen mitverursacht',
  ],

  GEHEIMNIS_GEGENWART: [
    'hat in einem früheren Fall Beweise manipuliert',
    'lebt unter falschem Namen',
    'finanziert heimlich die Konkurrenz',
    'hat eine heimliche Beziehung zur Zielperson',
    'versteckt eine hohe private Verschuldung',
    'war an einem nie aufgeklärten Unfall beteiligt',
  ],

  GEHEIMNIS_ZUKUNFT: [
    'trägt eine gefälschte Bio-Signatur',
    'schmuggelt verbotene Naniten für eine Untergrundzelle',
    'hat eine KI unautorisiert freigelassen',
    'ist ein inaktiver Schläferagent eines Konzerns',
    'verheimlicht einen fehlerhaften Gedächtnis-Upload',
    'hält Kontakt zu einer verbotenen außerkolonialen Fraktion',
  ],

  STIMME: [
    'rau und kratzig',
    'ruhig und warm',
    'hell und schnell',
    'tief und bedrohlich',
    'nasal und gedehnt',
    'leise und stockend',
    'klar und präzise',
    'brüchig vor Alter',
    'melodisch und singend',
    'hart und militärisch',
    'heiser durch Rauch',
    'hastig und druckvoll',
    'trocken und emotionslos',
    'freundlich, aber bestimmt',
    'scharf mit beißendem Unterton',
  ],

  WAFFE_MITTELALTER: [
    { name: 'Schwert', schadenswert: '2W10', kampfart: 'nahkampf', gewicht: 12 },
    { name: 'Langschwert', schadenswert: '2W10+1', kampfart: 'nahkampf', gewicht: 9 },
    { name: 'Kurzschwert', schadenswert: '1W10+2', kampfart: 'nahkampf', gewicht: 10 },
    { name: 'Streitaxt', schadenswert: '2W10+2', kampfart: 'nahkampf', gewicht: 8 },
    { name: 'Streitkolben', schadenswert: '2W10', kampfart: 'nahkampf', gewicht: 7 },
    { name: 'Dolch', schadenswert: '1W10', kampfart: 'nahkampf', gewicht: 11 },
    { name: 'Speer', schadenswert: '1W10+2', kampfart: 'nahkampf', gewicht: 10 },
    { name: 'Langbogen', schadenswert: '2W10', kampfart: 'fernkampf', gewicht: 7 },
    { name: 'Armbrust', schadenswert: '2W10+2', kampfart: 'fernkampf', gewicht: 6 },
  ],

  WAFFE_GEGENWART: [
    { name: 'Pistole', schadenswert: '2W10', kampfart: 'fernkampf', gewicht: 13 },
    { name: 'Revolver', schadenswert: '2W10+1', kampfart: 'fernkampf', gewicht: 9 },
    { name: 'Maschinenpistole', schadenswert: '2W10+2', kampfart: 'fernkampf', gewicht: 8 },
    { name: 'Sturmgewehr', schadenswert: '3W10', kampfart: 'fernkampf', gewicht: 8 },
    { name: 'Schrotflinte', schadenswert: '3W10+1', kampfart: 'fernkampf', gewicht: 6 },
    { name: 'Messer', schadenswert: '1W10+1', kampfart: 'nahkampf', gewicht: 11 },
    { name: 'Kampfmesser', schadenswert: '1W10+2', kampfart: 'nahkampf', gewicht: 8 },
    { name: 'Machete', schadenswert: '2W10', kampfart: 'nahkampf', gewicht: 6 },
    { name: 'Baseballschläger', schadenswert: '2W10', kampfart: 'nahkampf', gewicht: 5 },
    { name: 'Compoundbogen', schadenswert: '2W10+1', kampfart: 'fernkampf', gewicht: 4 },
  ],

  WAFFE_ZUKUNFT: [
    { name: 'Phaser', schadenswert: '3W10', kampfart: 'fernkampf', gewicht: 13 },
    { name: 'Strahlenpistole', schadenswert: '3W10', kampfart: 'fernkampf', gewicht: 11 },
    { name: 'Plasmagewehr', schadenswert: '4W10', kampfart: 'fernkampf', gewicht: 9 },
    { name: 'Impulsgewehr', schadenswert: '3W10+2', kampfart: 'fernkampf', gewicht: 8 },
    { name: 'Laserkarabiner', schadenswert: '3W10+1', kampfart: 'fernkampf', gewicht: 8 },
    { name: 'Railgun (Leicht)', schadenswert: '4W10+1', kampfart: 'fernkampf', gewicht: 5 },
    { name: 'Energieklinge', schadenswert: '2W10+3', kampfart: 'nahkampf', gewicht: 7 },
    { name: 'Molekulardolch', schadenswert: '2W10', kampfart: 'nahkampf', gewicht: 7 },
    { name: 'Nanitenklinge', schadenswert: '2W10+2', kampfart: 'nahkampf', gewicht: 6 },
  ],

  EINDRUCK: [
    'wirkt freundlich',
    'wirkt mürrisch',
    'wirkt nervös',
    'wirkt selbstsicher',
    'wirkt verschlossen',
    'wirkt neugierig',
    'wirkt müde',
    'wirkt heiter',
    'wirkt distanziert',
    'wirkt aufbrausend',
    'wirkt nachdenklich',
    'wirkt listig',
    'wirkt ehrlich',
    'wirkt verschmitzt',
    'wirkt grob',
    'wirkt fein',
    'wirkt gehetzt',
    'wirkt gelassen',
    'wirkt stolz',
    'wirkt demütig',
    'wirkt geheimnisvoll',
    'wirkt offenherzig',
    'wirkt paranoid',
    'wirkt verträumt',
    'wirkt pragmatisch',
  ],

  MERKMAL: [
    'auffällige Narbe',
    'fehlender Finger',
    'Tätowierung am Hals',
    'silberner Ring',
    'hölzerner Gehstock',
    'leiser Gang',
    'Humpeln',
    'falsches Auge',
    'silberne Haarsträhne',
    'Sommersprossen',
    'Goldzahn',
    'Brandmal am Handgelenk',
    'Amulett unter der Kleidung',
    'Singender Dialekt',
    'Zittern in der Hand',
    'auffällige Stimme',
    'duftet nach Lavendel',
    'trägt immer Handschuhe',
    'humpelnder Gehilfe',
    'Narbe quer über die Wange',
    'leuchtende Augenfarbe',
    'unruhige Hände',
    'pfeift unbewusst Melodien',
    'trägt einen fremdländischen Schmuck',
    'spricht mit leisem Lispeln',
    'hat ein kleines Muttermal',
  ],
};
