/**
 * Wortlisten für das Ort-Modul.
 */
window.HTBAH = window.HTBAH || {};

window.HTBAH.ZufallsgeneratorOrtListen = {
  PREFIX: [
    'Alt',
    'Neu',
    'Ober',
    'Nieder',
    'Klein',
    'Groß',
    'West',
    'Ost',
    'Nord',
    'Süd',
    'Mittel',
    'Hinter',
    'Vorder',
    'Rot',
    'Weiß',
    'Schwarz',
    'Grün',
    'Gold',
    'Silber',
    'Lang',
    'Kurz',
    'Hoch',
    'Tief',
  ],

  KERN: [
    'bach',
    'hausen',
    'feld',
    'burg',
    'dorf',
    'stein',
    'wald',
    'see',
    'furt',
    'mark',
    'tal',
    'rade',
    'kirchen',
    'brück',
    'münd',
    'werder',
    'au',
    'rode',
    'linden',
    'berg',
    'hof',
    'ried',
    'moor',
    'horn',
    'wind',
    'rain',
    'graben',
    'mühle',
    'garten',
    'wall',
    'tor',
    'kamp',
    'bruch',
    'heide',
    'winkel',
    'eck',
    'born',
  ],

  SUFFIX: [
    '',
    ' am Fluss',
    ' im Moor',
    ' an der Grenze',
    ' bei den Klippen',
    ' im Tal',
    ' an der Furt',
    ' am Wald',
    ' an der Küste',
    ' im Nebel',
    ' am Pass',
    ' an der Brücke',
    ' beim alten Turm',
    ' am See',
    ' in den Auen',
  ],

  GROESSE: [
    'Weiler',
    'Dorf',
    'Kleinstadt',
    'Mittelstadt',
    'Stadt',
    'Hafenstadt',
    'Marktflecken',
    'Siedlung',
    'Bergwerkssiedlung',
    'Klosterhof',
    'Burgflecken',
    'Außenbezirk',
    'Metropole',
    'Handelsstadt',
    'Festung',
  ],

  LAGE: [
    'Hügelland',
    'Küste',
    'Wald',
    'Flusstal',
    'Gebirgspass',
    'Insel',
    'Steppe',
    'Sumpf',
    'Seenplatte',
    'Ebene',
    'Marschland',
    'Hochmoor',
    'Klippenküste',
    'Fjord',
    'Wüstenrand',
    'Oase',
    'Vulkanhang',
    'Gletschertal',
    'Tiefland',
    'Grenzregion',
  ],

  ZUSTAND: [
    'florierend',
    'belebt',
    'heruntergekommen',
    'wiederaufgebaut',
    'kriegsgezeichnet',
    'friedlich',
    'verlassen wirkend',
    'wachsend',
    'von Pilgerströmen geprägt',
    'von Banditen geplagt',
    'unter Quarantäne',
    'festlich geschmückt',
    'von Sturm heimgesucht',
    'mit leeren Häusern',
    'von Händlern überflutet',
  ],

  GERUECHT: [
    'Gerüchte über einen alten Pakt.',
    'Die Brunnen sollen magisch sein.',
    'Letztes Jahr brannte die Scheune.',
    'Fremde werden misstrauisch beäugt.',
    'Ein Fest steht bevor.',
    'Der Bürgermeister gilt als korrupt.',
    'Ein Geist soll am Brunnen sitzen.',
    'Die Kinder erzählen von einem Licht im Wald.',
    'Ein Fremder hat viel Gold ausgegeben.',
    'Die Schmiede arbeitet nachts.',
    'Die Kirche ist verriegelt.',
    'Ein Heiler soll Gift verkaufen.',
    'Die alte Mühle ist wieder in Betrieb.',
    'Seit der Flut fehlen drei Einwohner.',
    'Ein Wanderer verschwand spurlos.',
    'Die Glocken läuten ohne Zieher.',
    'Ein Pakt mit dem Fluss soll bestehen.',
    'Die Taverne hat neue Besitzer.',
    'Ein Wappen wurde gestohlen.',
    'Die Brücke muss repariert werden.',
  ],

  BEKANNT_FUER: [
    'Fischfang',
    'Bierbrauerei',
    'Schmiedekunst',
    'Markt',
    'Tempel',
    'Schmuggel',
    'Spitzenweine',
    'Wollhandel',
    'Salzverladung',
    'Pergament',
    'Kräuter',
    'Musikfest',
    'Schwerter',
    'Kerzen',
    'Honig',
    'Pferdezucht',
    'Glasmalerei',
    'Uhrmacher',
    'Teppiche',
    'Obsidian',
  ],
};
