/**
 * Wortlisten für das Ort-Modul.
 */
window.HTBAH = window.HTBAH || {};

window.HTBAH.ZufallsgeneratorOrtListen = {
  PREFIX: [
    'Alt',
    'Neu',
    'Ober',
    'Nieder',
    'Klein',
    'Groß',
    'West',
    'Ost',
    'Nord',
    'Süd',
    'Mittel',
    'Hinter',
    'Vorder',
    'Rot',
    'Weiß',
    'Schwarz',
    'Grün',
    'Gold',
    'Silber',
    'Lang',
    'Kurz',
    'Hoch',
    'Tief',
  ],

  KERN: [
    'bach',
    'hausen',
    'feld',
    'burg',
    'dorf',
    'stein',
    'wald',
    'see',
    'furt',
    'mark',
    'tal',
    'rade',
    'kirchen',
    'brück',
    'münd',
    'werder',
    'au',
    'rode',
    'linden',
    'berg',
    'hof',
    'ried',
    'moor',
    'horn',
    'wind',
    'rain',
    'graben',
    'mühle',
    'garten',
    'wall',
    'tor',
    'kamp',
    'bruch',
    'heide',
    'winkel',
    'eck',
    'born',
  ],

  SUFFIX: [
    '',
    ' am Fluss',
    ' im Moor',
    ' an der Grenze',
    ' bei den Klippen',
    ' im Tal',
    ' an der Furt',
    ' am Wald',
    ' an der Küste',
    ' im Nebel',
    ' am Pass',
    ' an der Brücke',
    ' beim alten Turm',
    ' am See',
    ' in den Auen',
  ],

  GROESSE: [
    'Weiler',
    'Dorf',
    'Kleinstadt',
    'Mittelstadt',
    'Stadt',
    'Hafenstadt',
    'Marktflecken',
    'Siedlung',
    'Bergwerkssiedlung',
    'Klosterhof',
    'Burgflecken',
    'Außenbezirk',
    'Metropole',
    'Handelsstadt',
    'Festung',
  ],

  LAGE: [
    'Hügelland',
    'Küste',
    'Wald',
    'Flusstal',
    'Gebirgspass',
    'Insel',
    'Steppe',
    'Sumpf',
    'Seenplatte',
    'Ebene',
    'Marschland',
    'Hochmoor',
    'Klippenküste',
    'Fjord',
    'Wüstenrand',
    'Oase',
    'Vulkanhang',
    'Gletschertal',
    'Tiefland',
    'Grenzregion',
  ],

  ZUSTAND: [
    'florierend',
    'belebt',
    'heruntergekommen',
    'wiederaufgebaut',
    'kriegsgezeichnet',
    'friedlich',
    'verlassen wirkend',
    'wachsend',
    'von Pilgerströmen geprägt',
    'von Banditen geplagt',
    'unter Quarantäne',
    'festlich geschmückt',
    'von Sturm heimgesucht',
    'mit leeren Häusern',
    'von Händlern überflutet',
  ],

  ZUSTAND_GEGENWART: [
    'gentrifiziert',
    'sanierungsbedürftig',
    'überfüllt',
    'verkehrsberuhigt',
    'im Umbau',
    'von Touristen frequentiert',
    'wirtschaftlich angespannt',
    'digital vernetzt',
    'von Baustellen geprägt',
    'ökologisch aufgewertet',
    'nachts lebendig',
    'tagsüber geschäftig',
    'von Leerstand gezeichnet',
    'multikulturell',
    'von Protesten aufgewühlt',
  ],

  ZUSTAND_ZUKUNFT: [
    'terraformiert',
    'unter Kuppel',
    'energieautark',
    'von Drohnen überwacht',
    'teilweise evakuiert',
    'im Wachstum',
    'von Stromausfällen betroffen',
    'militärisch gesichert',
    'handelsaktiv',
    'von Sandstürmen bedroht',
    'in Schwerelosigkeit betrieben',
    'von KI verwaltet',
    'quarantänisiert',
    'von Schrottsammlern bevölkert',
    'wissenschaftlich genutzt',
  ],

  ATMOSPHAERE: [
    'Rauch und feuchtes Stroh liegen in den Gassen.',
    'Marktschreier und Hufgetrappel bestimmen den Alltag.',
    'Alte Steine atmen Geschichte; Kerzen flackern hinter schmalen Fenstern.',
    'Der Geruch von Brot und Leder hängt über dem Platz.',
    'Nebel zieht vom Fluss herauf, wenn die Glocken läuten.',
    'Händler feilschen laut; Kinder rennen zwischen Karren hindurch.',
    'Die Stadtmauer wirft lange Schatten auf schmale Pfade.',
    'Ein fernes Lied dringt aus der Taverne, gemischt mit Hundegebell.',
    'Regen prasselt auf Schindeln; Rauch steigt aus vielen Schornsteinen.',
    'Pilger und Bettler teilen sich die Brücke am Morgen.',
  ],

  ATMOSPHAERE_GEGENWART: [
    'Verkehrslärm und Baustellen bestimmen das Straßenbild.',
    'Hinter Glasfassaden flimmern Bildschirme bis spät in die Nacht.',
    'Der Duft von Kaffee und Abgasen mischt sich am Bahnhofsvorplatz.',
    'Graffiti, Fahrräder und Lieferdienste prägen den Alltag.',
    'Smartphone-Licht tanzt über dem nächtlichen Gehweg.',
    'Alte Fabrikhallen wurden zu Lofts und Galerien umgebaut.',
    'An Haltestellen warten Pendler mit Kopfhörern und Kaffeebechern.',
    'Regen spiegelt Neonreklamen auf nassem Asphalt.',
    'Im Park joggt man zwischen Müllcontainern und Spielplätzen.',
    'Die U-Bahn-Ausgänge speien Menschen in alle Richtungen.',
  ],

  ATMOSPHAERE_ZUKUNFT: [
    'Neonreflexe gleiten über Kuppelwände und Metallböden.',
    'Leises Summen der Lebenserhaltung ist überall hörbar.',
    'Schwebende Werbetafeln blinken in synthetischen Farben.',
    'Schwerkraftwechsel lassen Schritte leicht oder schwer wirken.',
    'Fernes Dröhnen von Frachtern hallt durch die Schleusen.',
    'Kühle Luft riecht nach Ozon und recyceltem Wasser.',
    'Drohnen kreuzen zwischen Türmen wie mechanische Vögel.',
    'Hologramme weisen den Weg durch labyrinthartige Gänge.',
    'Unter der Kuppel wechseln Tag und Nacht künstlich.',
    'Fremdartige Pflanzen wachsen in kontrollierten Biotopen.',
  ],

  GERUECHT: [
    'Gerüchte über einen alten Pakt.',
    'Die Brunnen sollen magisch sein.',
    'Letztes Jahr brannte die Scheune.',
    'Fremde werden misstrauisch beäugt.',
    'Ein Fest steht bevor.',
    'Der Bürgermeister gilt als korrupt.',
    'Ein Geist soll am Brunnen sitzen.',
    'Die Kinder erzählen von einem Licht im Wald.',
    'Ein Fremder hat viel Gold ausgegeben.',
    'Die Schmiede arbeitet nachts.',
    'Die Kirche ist verriegelt.',
    'Ein Heiler soll Gift verkaufen.',
    'Die alte Mühle ist wieder in Betrieb.',
    'Seit der Flut fehlen drei Einwohner.',
    'Ein Wanderer verschwand spurlos.',
    'Die Glocken läuten ohne Zieher.',
    'Ein Pakt mit dem Fluss soll bestehen.',
    'Die Taverne hat neue Besitzer.',
    'Ein Wappen wurde gestohlen.',
    'Die Brücke muss repariert werden.',
  ],

  BEKANNT_FUER: [
    'Fischfang',
    'Bierbrauerei',
    'Schmiedekunst',
    'Markt',
    'Tempel',
    'Schmuggel',
    'Spitzenweine',
    'Wollhandel',
    'Salzverladung',
    'Pergament',
    'Kräuter',
    'Musikfest',
    'Schwerter',
    'Kerzen',
    'Honig',
    'Pferdezucht',
    'Glasmalerei',
    'Uhrmacher',
    'Teppiche',
    'Obsidian',
  ],

  /** Gegenwart: Namensbausteine */
  GEGENWART_PREFIX: [
    'Neu',
    'Alt',
    'Ober',
    'Nord',
    'Süd',
    'West',
    'Ost',
    'Klein',
    'Groß',
    'Grün',
    'Sonnen',
    'Wasser',
    'Berg',
    'Park',
    'Hafen',
    'Industrie',
  ],
  GEGENWART_KERN: [
    'stadt',
    'dorf',
    'viertel',
    'bezirk',
    'park',
    'höhe',
    'tal',
    'feld',
    'see',
    'brücke',
    'ring',
    'platz',
    'ufer',
    'garten',
    'center',
    'bahnhof',
    'hafen',
    'markt',
    'allee',
    'weg',
  ],
  GEGENWART_SUFFIX: [
    '',
    ' am Fluss',
    ' an der Autobahn',
    ' im Gewerbegebiet',
    ' am Stadtrand',
    ' bei den Gleisen',
    ' am Hafen',
    ' im Grünen',
    ' an der Küste',
    ' im Tal',
    ' am See',
  ],

  /** Zukunft: Namensbausteine */
  ZUKUNFT_PREFIX: [
    'Neo',
    'Nova',
    'Alpha',
    'Omega',
    'Terra',
    'Luna',
    'Orion',
    'Helix',
    'Astra',
    'Nexus',
    'Prime',
    'Zero',
    'Deep',
    'High',
    'Free',
    'New',
  ],
  ZUKUNFT_KERN: [
    'haven',
    'port',
    'station',
    'dome',
    'sector',
    'ring',
    'spire',
    'hub',
    'colony',
    'outpost',
    'arc',
    'vault',
    'gate',
    'plex',
    'forge',
    'reach',
    'strand',
    'field',
    'line',
    'point',
  ],
  ZUKUNFT_SUFFIX: [
    '',
    ' Prime',
    ' IX',
    ' Delta',
    ' am Orbit',
    ' im Asteroidengürtel',
    ' an der Grenze',
    ' Unterstadt',
    ' Oberring',
    ' Sektor 7',
    ' am Nexus',
  ],

  GROESSE_GEGENWART: [
    'Vorort',
    'Großstadt',
    'Industriegebiet',
    'Einkaufszentrum',
    'Campus',
    'Satellitenstadt',
    'Feriensiedlung',
    'Logistikzentrum',
    'Bürokomplex',
    'Wohnblock',
  ],

  GROESSE_ZUKUNFT: [
    'Orbitalstation',
    'Raumhafen',
    'Terraform-Kolonie',
    'Untergrundkomplex',
    'Arcologie',
    'Asteroidenbasis',
    'Mondkolonie',
    'Freihafen-Modul',
    'Forschungsdom',
    'Exo-Settlement',
  ],

  LAGE_GEGENWART: [
    'Autobahnkreuz',
    'Industriepark',
    'Flughafen-Nähe',
    'Uferpromenade',
    'Hochhausinsel',
    'Einkaufsmeile',
    'Gewerbegebiet',
    'Naturschutzgebiet',
    'Binnenhafen',
    'Pendlerregion',
  ],

  LAGE_ZUKUNFT: [
    'Asteroidengürtel',
    'Terraform-Zone',
    'Null-Schwerkraft',
    'Mondkrater',
    'Orbitalring',
    'Tiefsee-Druckkuppel',
    'Mars-Äquator',
    'Europa-Eis',
    'Lagrange-Punkt',
    'Warp-Grenze',
  ],

  GERUECHT_GEGENWART: [
    'Ein Startup will hier ansiedeln.',
    'Die Mieten steigen seit Monaten.',
    'Ein Datenleck betrifft die Verwaltung.',
    'Proteste gegen ein Bauprojekt.',
    'Die Polizei kontrolliert häufiger.',
    'Ein Influencer hat den Ort entdeckt.',
    'Die alte Fabrik soll abgerissen werden.',
    'Ein Festival zieht Besucher an.',
    'Die U-Bahn-Anbindung ist umstritten.',
    'Ein Skandal um die Bürgermeisterin.',
  ],

  GERUECHT_ZUKUNFT: [
    'Die KI-Verwaltung trifft umstrittene Entscheidungen.',
    'Ein Frachter ist im Orbit verschwunden.',
    'Sabotage an der Sauerstoffanlage wird vermutet.',
    'Fremde Signale aus dem Untergrund.',
    'Ein Schwarzmarkt für Gene-Tech floriert.',
    'Die Schwerkraft-Regulierung fällt sporadisch aus.',
    'Pilger suchen ein altes Artefakt.',
    'Ein Exodus-Schiff soll landen.',
    'Die Kuppel wurde verstärkt – Grund unklar.',
    'Hacker haben die Lichtsteuerung übernommen.',
  ],

  BEKANNT_FUER_GEGENWART: [
    'Streetfood',
    'Start-up-Szene',
    'Nachtleben',
    'Öffentlicher Verkehr',
    'Street Art',
    'Bio-Markt',
    'Tech-Hub',
    'Festivals',
    'Craft Beer',
    'Coworking',
  ],

  BEKANNT_FUER_ZUKUNFT: [
    'Null-g-Schwerkraft-Sport',
    'Synth-Produktion',
    'Orbital-Handel',
    'Terraform-Forschung',
    'Kybernetik-Klinik',
    'Drohnenlogistik',
    'Energie-Export',
    'Exo-Botanik',
    'Warp-Aufbereitung',
    'KI-Mediation',
  ],
};
