/**
 * Wortlisten für den Pantheon-/Gottheiten-Zufallsgenerator.
 */
window.HTBAH = window.HTBAH || {};

window.HTBAH.ZufallsgeneratorPantheonListen = {
  NAMEN_PREFIX: [
    'Ara',
    'Bel',
    'Cel',
    'Dor',
    'Eth',
    'Fae',
    'Gor',
    'Hel',
    'Ith',
    'Kor',
    'Lun',
    'Mor',
    'Nyx',
    'Oph',
    'Pel',
    'Ryn',
    'Syl',
    'Tor',
    'Ulr',
    'Vey',
    'Xan',
    'Ydr',
    'Zae',
  ],
  NAMEN_SUFFIX: [
    'thos',
    'iel',
    'ara',
    'une',
    'axis',
    'ion',
    'astra',
    'veth',
    'mira',
    'kos',
    'indra',
    'shen',
    'vok',
    'riel',
    'thar',
  ],
  NAMEN_TITEL: [
    'die Spaltende',
    'der Stille Pfeiler',
    'die Zweite Sonne',
    'der Krumme Weg',
    'die Unterzeichnete',
    'der Leere Kelch',
    'die Brennende Krone',
    'der Ferne Hammer',
    'die Siebte Schwester',
    'der Verlorene Schlüssel',
  ],

  GESCHLECHT: [
    'als männlich dargestellt',
    'als weiblich dargestellt',
    'geschlechtslos / ohne feste Form',
    'wechselt Darstellung je nach Kultur',
    'als mehrere Geschlechter zugleich dargestellt',
    'als Kind / Alter / Jungfer — je nach Epoche',
    'nicht menschlich anthropomorphisiert (Tier, Objekt)',
  ],

  DOMAENEN: [
    'Feuer, Schmieden und Zorn',
    'Heilung, Kräuter und Geburt',
    'Diebstahl, Schatten und Glücksspiel',
    'Krieg, Ehre und Wettkampf',
    'Tod, Übergänge und Ahnen',
    'Wasser, Stürme und Fischfang',
    'Ernte, Boden und Speise',
    'Recht, Verträge und Strafen',
    'Musik, Trunk und Ekstase',
    'Schrift, Archive und Geheimnisse',
    'Reisen, Wege und Türen',
    'Schmuck, Liebe und Eifersucht',
    'Schnee, Kälte und Stille',
    'Schlangen, Gift und Heilmittel',
    'Uhren, Fristen und Schicksal',
  ],

  CHARAKTER: [
    'gütig und langmütig',
    'rachsüchtig und unvergesslich',
    'launisch, fast kindlich',
    'kalt, distanziert, „gerecht“',
    'verrückt im Mythos — Orakel unlesbar',
    'pragmatisch, handelsorientiert',
    'neidisch auf andere Gottheiten',
    'schuldversessen, ritualisiert',
    'verschmitzt, liebt Streiche',
    'melancholisch, sucht Trost bei Sterblichen',
    'wollüstig, grenzüberschreitend',
    'stolz, leicht beleidigt',
  ],

  STAERKEN: [
    'unerschütterliche Treue der eigenen Priesterschaft',
    'schnelle Wunder in Notfällen — aber teuer',
    'überragende Prophetie in Träumen',
    'Schutz vor einem bestimmten Übel (Gift, Feuer, …)',
    'Reichtum an Symbolen und Festen — starke Präsenz im Alltag',
    'Netzwerk mit anderen Kulten — Diplomatie',
  ],

  SCHWAECHEN: [
    'lässt sich durch bestimmte Tabus blockieren',
    'schwach außerhalb geweihter Orte',
    'verlangt ständige Opfer — sonst „schläft“ der Segen',
    'eifersüchtig auf Rivalen — Segen kippt in Fluch',
    'unberechenbar: Angebetete verstehen die Zeichen falsch',
    'historisch umstritten — Spaltung der Gläubigen',
  ],

  SCHUTZPATRONAT: [
    'Schmiede, Hufschmiede, Metallarbeiter',
    'Hebammen und Krankenwärter',
    'Diebe, Gaukler, Grenzgänger',
    'Soldaten vor der ersten Schlacht',
    'Totengräber, Bestatter, Trauernde',
    'Fischer, Seeleute, Hafenarbeiter',
    'Bauern, Müller, Bäcker',
    'Richter, Schreiber, Vertragsmacher',
    'Sänger, Poeten, Trunkenbolde',
    'Bibliothekare, Kopisten, Alchimisten',
    'Wanderer, Karawanen, Postboten',
    'Kinder, Findelkinder, Waisen',
  ],

  VERLANGEN: [
    'blutlose Opfer bei Neumond',
    'Stille eines ganzen Tages im Jahr',
    'einen wahren Geständnisakt in der Schrift',
    'ein Symbol der Rivalen — verbrannt oder versenkt',
    'Fasten und Tanz bis zur Erschöpfung',
    'ein Kind benennen nach dem Gott — lebenslange Bindung',
    'Gold in den Tempel — „Zins an den Himmel“',
    'kein Lügenwort an Heiligtagen',
  ],

  MYTHOS_GABEN: [
    'Man sagt, sie schenke ein einziges Wunder — dann sei die Schuld beglichen.',
    'Gerüchte sprechen von einem Schlüssel, den nur sie verstecken kann.',
    'Die Alten behaupten, sie habe einmal einen ganzen Stamm gerettet — und nie vergessen.',
    'Es heißt, ihr Segen fühle sich warm an wie Kohle — und brenne leise, wenn man sie verrät.',
    'Man erzählt, sie gebe Glück im Spiel — aber nie zweimal am selben Ort.',
    'Priesterinnen schwören: In der letzten Stunde spricht sie durch den Wind.',
    'Kinder sagen, sie lasse kleine Gaben unter Kissen — wenn man brav war.',
    'Skeptiker meinen, der Segen sei nur Disziplin — Gläubige lachen.',
  ],

  KULT_STIMMUNG: [
    'öffentlich geduldet, privat geliebt',
    'nur in einer Region wirklich präsent',
    'verboten — aber überall',
    'elitär, teure Einweihung',
    'volksnah, laut, farbenfroh',
    'ritualisiert und streng hierarchisch',
    'in den Adelshäusern präsent, im Dorf versteckt',
    'von Wanderpredigern getragen',
  ],

  KULT_STIMMUNG_GEGENWART: [
    'als Verein registriert — Glaube optional',
    'online präsent, offline fragmentiert',
    'nur noch ältere Generation aktiv',
    'im Trend bei Jugendlichen',
    'von Behörden toleriert, von Medien belächelt',
    'mit Esoterik-Szene vermischt',
    'streng abgeschottet, kaum öffentlich',
    'spendet sichtbar — wirkt wohltätig',
  ],

  KULT_STIMMUNG_ZUKUNFT: [
    'als KI-Kult offiziell anerkannt',
    'nur in einer Kolonie präsent',
    'verboten — aber in Datennetzen lebendig',
    'elitär, nur mit Implantat-Zugang',
    'volksnah über Holo-Predigten',
    'von Söldnern und Piloten verehrt',
    'ritualisiert in Druckkammern',
    'von Wissenschaftlern als „Metapher“ abgetan',
  ],

  RIVALE: [
    'eine Wassergottheit, mit der sie ewige Fehde hat',
    'ein abtrünniger Heiliger, der als Dämon läuft',
    'ein sterblicher Held, den sie neidisch macht',
    'niemand — sie ist isoliert und seltsam',
    'ein Schatten-Zwilling im Mythos',
    'eine vergessene Schwestergottheit',
    'ein sterblicher König, der sie einst betrog',
    'ein Naturgeist ohne Namen',
  ],

  RIVALE_GEGENWART: [
    'eine NGO, die den Kult „entzaubert“',
    'ein Influencer-Priester einer Konkurrenz',
    'ein skeptischer Wissenschaftler mit großer Reichweite',
    'eine andere Glaubensgemeinschaft im selben Viertel',
    'niemand Sichtbares — nur innere Spaltung',
    'ein Skandal um alte Führungsfiguren',
    'ein Medienbericht, der alles ins Wanken bringt',
    'ein anonymes Online-Forum voller Häresie',
  ],

  RIVALE_ZUKUNFT: [
    'eine KI-Gottheit aus einem anderen Sektor',
    'ein abtrünniger Kult mit ähnlicher Domäne',
    'ein sterblicher Admiral, der Segen verweigert',
    'niemand — sie ist in Archiven fast gelöscht',
    'ein Datenvirus, der Gebete verfälscht',
    'eine Terraform-KI mit konkurrierender Agenda',
    'ein Prophet, der behauptet, die Gottheit sei tot',
    'ein Schwarzmarkt-Kult mit billigeren Wundern',
  ],

  ATMOSPHAERE: [
    'Weihrauch und alte Lieder prägen den Tempel.',
    'Pilger hinterlassen kleine Opfer am Rand des Weges.',
    'Priester sprechen in Formeln, die niemand mehr versteht.',
    'Das Symbol der Gottheit ist überall — diskret oder prunkvoll.',
    'Gerüchte über Wunder halten den Glauben am Leben.',
  ],

  ATMOSPHAERE_GEGENWART: [
    'Kerzen und LED-Lichter mischen sich in einem Hinterzimmer.',
    'Ein Podcast zitiert die Gottheit — ironisch oder ernst?',
    'Sticker und Schmuck tragen das heilige Zeichen.',
    'Der Kult trifft sich samstags in einem Gemeindesaal.',
    'Soziale Medien verbreiten Gebete schneller als Predigten.',
  ],

  ATMOSPHAERE_ZUKUNFT: [
    'Holo-Altäre flackern in der Schwerelosigkeit.',
    'Gebete werden als Datenpakete übertragen.',
    'Das Symbol leuchtet auf Kuppeln ganzer Sektoren.',
    'Pilger reisen per Shuttle — nicht zu Fuß.',
    'Rituale mischen Archaik und Nanotechnologie.',
  ],

  SCHUTZPATRONAT_GEGENWART: [
    'Programmierer und IT-Techniker',
    'Kurierfahrer und Lieferdienste',
    'Pflegekräfte und Sanitäter',
    'Journalisten und Whistleblower',
    'Startup-Gründer',
    'Nachtschicht-Arbeiter',
    'Straßenmusiker und Künstler',
    'Ermittler und Detektive',
  ],

  SCHUTZPATRONAT_ZUKUNFT: [
    'Frachterpiloten und Dockarbeiter',
    'Terraform-Ingenieure',
    'Kybernetik-Chirurgen',
    'Schmuggler und Grenzgänger',
    'KI-Moderatoren',
    'Exo-Biologen',
    'Kolonie-Gründer',
    'Söldner vor dem Sprung',
  ],
};
