/**
 * Wortlisten für den Pantheon-/Gottheiten-Zufallsgenerator.
 */
window.HTBAH = window.HTBAH || {};

window.HTBAH.ZufallsgeneratorPantheonListen = {
  NAMEN_PREFIX: [
    'Ara',
    'Bel',
    'Cel',
    'Dor',
    'Eth',
    'Fae',
    'Gor',
    'Hel',
    'Ith',
    'Kor',
    'Lun',
    'Mor',
    'Nyx',
    'Oph',
    'Pel',
    'Ryn',
    'Syl',
    'Tor',
    'Ulr',
    'Vey',
    'Xan',
    'Ydr',
    'Zae',
  ],
  NAMEN_SUFFIX: [
    'thos',
    'iel',
    'ara',
    'une',
    'axis',
    'ion',
    'astra',
    'veth',
    'mira',
    'kos',
    'indra',
    'shen',
    'vok',
    'riel',
    'thar',
  ],
  NAMEN_TITEL: [
    'die Spaltende',
    'der Stille Pfeiler',
    'die Zweite Sonne',
    'der Krumme Weg',
    'die Unterzeichnete',
    'der Leere Kelch',
    'die Brennende Krone',
    'der Ferne Hammer',
    'die Siebte Schwester',
    'der Verlorene Schlüssel',
  ],

  GESCHLECHT: [
    'als männlich dargestellt',
    'als weiblich dargestellt',
    'geschlechtslos / ohne feste Form',
    'wechselt Darstellung je nach Kultur',
    'als mehrere Geschlechter zugleich dargestellt',
    'als Kind / Alter / Jungfer — je nach Epoche',
    'nicht menschlich anthropomorphisiert (Tier, Objekt)',
  ],

  DOMAENEN: [
    'Feuer, Schmieden und Zorn',
    'Heilung, Kräuter und Geburt',
    'Diebstahl, Schatten und Glücksspiel',
    'Krieg, Ehre und Wettkampf',
    'Tod, Übergänge und Ahnen',
    'Wasser, Stürme und Fischfang',
    'Ernte, Boden und Speise',
    'Recht, Verträge und Strafen',
    'Musik, Trunk und Ekstase',
    'Schrift, Archive und Geheimnisse',
    'Reisen, Wege und Türen',
    'Schmuck, Liebe und Eifersucht',
    'Schnee, Kälte und Stille',
    'Schlangen, Gift und Heilmittel',
    'Uhren, Fristen und Schicksal',
  ],

  CHARAKTER: [
    'gütig und langmütig',
    'rachsüchtig und unvergesslich',
    'launisch, fast kindlich',
    'kalt, distanziert, „gerecht“',
    'verrückt im Mythos — Orakel unlesbar',
    'pragmatisch, handelsorientiert',
    'neidisch auf andere Gottheiten',
    'schuldversessen, ritualisiert',
    'verschmitzt, liebt Streiche',
    'melancholisch, sucht Trost bei Sterblichen',
    'wollüstig, grenzüberschreitend',
    'stolz, leicht beleidigt',
  ],

  STAERKEN: [
    'unerschütterliche Treue der eigenen Priesterschaft',
    'schnelle Wunder in Notfällen — aber teuer',
    'überragende Prophetie in Träumen',
    'Schutz vor einem bestimmten Übel (Gift, Feuer, …)',
    'Reichtum an Symbolen und Festen — starke Präsenz im Alltag',
    'Netzwerk mit anderen Kulten — Diplomatie',
  ],

  SCHWAECHEN: [
    'lässt sich durch bestimmte Tabus blockieren',
    'schwach außerhalb geweihter Orte',
    'verlangt ständige Opfer — sonst „schläft“ der Segen',
    'eifersüchtig auf Rivalen — Segen kippt in Fluch',
    'unberechenbar: Angebetete verstehen die Zeichen falsch',
    'historisch umstritten — Spaltung der Gläubigen',
  ],

  SCHUTZPATRONAT: [
    'Schmiede, Hufschmiede, Metallarbeiter',
    'Hebammen und Krankenwärter',
    'Diebe, Gaukler, Grenzgänger',
    'Soldaten vor der ersten Schlacht',
    'Totengräber, Bestatter, Trauernde',
    'Fischer, Seeleute, Hafenarbeiter',
    'Bauern, Müller, Bäcker',
    'Richter, Schreiber, Vertragsmacher',
    'Sänger, Poeten, Trunkenbolde',
    'Bibliothekare, Kopisten, Alchimisten',
    'Wanderer, Karawanen, Postboten',
    'Kinder, Findelkinder, Waisen',
  ],

  VERLANGEN: [
    'blutlose Opfer bei Neumond',
    'Stille eines ganzen Tages im Jahr',
    'einen wahren Geständnisakt in der Schrift',
    'ein Symbol der Rivalen — verbrannt oder versenkt',
    'Fasten und Tanz bis zur Erschöpfung',
    'ein Kind benennen nach dem Gott — lebenslange Bindung',
    'Gold in den Tempel — „Zins an den Himmel“',
    'kein Lügenwort an Heiligtagen',
  ],

  MYTHOS_GABEN: [
    'Man sagt, sie schenke ein einziges Wunder — dann sei die Schuld beglichen.',
    'Gerüchte sprechen von einem Schlüssel, den nur sie verstecken kann.',
    'Die Alten behaupten, sie habe einmal einen ganzen Stamm gerettet — und nie vergessen.',
    'Es heißt, ihr Segen fühle sich warm an wie Kohle — und brenne leise, wenn man sie verrät.',
    'Man erzählt, sie gebe Glück im Spiel — aber nie zweimal am selben Ort.',
    'Priesterinnen schwören: In der letzten Stunde spricht sie durch den Wind.',
    'Kinder sagen, sie lasse kleine Gaben unter Kissen — wenn man brav war.',
    'Skeptiker meinen, der Segen sei nur Disziplin — Gläubige lachen.',
  ],
};
