/**
 * Vorgegebene Fähigkeiten-Presets (How to be a Hero: Fähigkeitsnamen je Begabung).
 * Werte sind bewusst leer — Spielende verteilen die 400 Punkte selbst.
 * Charaktervorlagen und Demo-Archetypen nutzen ausschließlich Namen aus diesen Listen.
 * @see https://howtobeahero.de/index.php/Fähigkeiten
 */
window.HTBAH_STANDARD_FAEHIGKEITEN_PRESETS = [
  {
    htbahPresetId: 'htbah-mittelalter-fantasy',
    name: 'Mittelalter/Fantasy',
    handeln: [
      { name: 'Schlösser knacken', value: null },
      { name: 'Nahkampf (bewaffnet)', value: null },
      { name: 'Nahkampf (unbewaffnet)', value: null },
      { name: 'Fernkampf', value: null },
      { name: 'Reiten', value: null },
      { name: 'Schleichen', value: null },
      { name: 'Klettern', value: null },
      { name: 'Athletik', value: null },
      { name: 'Schwimmen', value: null },
      { name: 'Heben & Tragen', value: null },
    ],
    wissen: [
      { name: 'Magiekunde', value: null },
      { name: 'Geschichte & Legenden', value: null },
      { name: 'Heilkunde', value: null },
      { name: 'Religion', value: null },
      { name: 'Physik & Mechanik', value: null },
      { name: 'Alte Sprachen', value: null },
      { name: 'Tierkunde & -dressur', value: null },
      { name: 'Geografie', value: null },
      { name: 'Überleben (Wildnis)', value: null },
      { name: 'Wahrnehmung', value: null },
      { name: 'Pflanzenkunde', value: null },
      { name: 'Magischer Trick', value: null },
    ],
    soziales: [
      { name: 'Überreden', value: null },
      { name: 'Einschüchtern', value: null },
      { name: 'Etikette & Anstand', value: null },
      { name: 'Handel & Feilschen', value: null },
      { name: 'Lügen', value: null },
      { name: 'Menschenkenntnis', value: null },
      { name: 'Auftreten', value: null },
      { name: 'Diplomatie', value: null },
      { name: 'Verführen', value: null },
      { name: 'Begeistern', value: null },
    ],
  },
  {
    htbahPresetId: 'htbah-gegenwart',
    /** @deprecated Legacy-ID aus älteren Speicherständen */
    legacyPresetIds: ['htbah-zombie-apokalypse'],
    name: 'Gegenwart',
    handeln: [
      { name: 'Schusswaffen', value: null },
      { name: 'Nahkampf', value: null },
      { name: 'Schleichen', value: null },
      { name: 'Athletik', value: null },
      { name: 'Fahren', value: null },
      { name: 'Reparieren', value: null },
      { name: 'Klettern', value: null },
      { name: 'Heben & Tragen', value: null },
    ],
    wissen: [
      { name: 'Medizin & Erste Hilfe', value: null },
      { name: 'Technik & Elektronik', value: null },
      { name: 'Überleben (urban)', value: null },
      { name: 'Mechanik', value: null },
      { name: 'Chemie (Basis)', value: null },
      { name: 'Orientierung', value: null },
      { name: 'Computer', value: null },
      { name: 'Wahrnehmung', value: null },
    ],
    soziales: [
      { name: 'Führung', value: null },
      { name: 'Überreden', value: null },
      { name: 'Einschüchtern', value: null },
      { name: 'Lügen', value: null },
      { name: 'Menschenkenntnis', value: null },
      { name: 'Verhandeln', value: null },
      { name: 'Motivation (Gruppe)', value: null },
      { name: 'Begeistern', value: null },
    ],
  },
  {
    htbahPresetId: 'htbah-scifi',
    name: 'Sci-Fi',
    handeln: [
      { name: 'Laserwaffen', value: null },
      { name: 'Plasmawaffen', value: null },
      { name: 'Raumschiff-Pilotieren', value: null },
      { name: 'Drohnensteuerung', value: null },
      { name: 'Schwerelosigkeits-Manöver', value: null },
      { name: 'Exoanzug-Einsatz', value: null },
      { name: 'Nahkampf (Energiewaffen)', value: null },
      { name: 'Wartung & Reparatur', value: null },
      { name: 'Schleichen', value: null },
    ],
    wissen: [
      { name: 'Astrophysik', value: null },
      { name: 'Xenobiologie', value: null },
      { name: 'Sternenkartografie', value: null },
      { name: 'Raumschifftechnik', value: null },
      { name: 'KI-Systeme', value: null },
      { name: 'Cybernetik', value: null },
      { name: 'Planetare Ökologie', value: null },
      { name: 'Fremdsprachen (außerirdisch)', value: null },
      { name: 'Wahrnehmung', value: null },
    ],
    soziales: [
      { name: 'Diplomatie (interstellar)', value: null },
      { name: 'Verhandeln', value: null },
      { name: 'Kulturelle Anpassung', value: null },
      { name: 'Menschenkenntnis', value: null },
      { name: 'Außerirdische Spezies deuten', value: null },
      { name: 'Führung (Crew)', value: null },
      { name: 'Überzeugen', value: null },
      { name: 'Einschüchtern', value: null },
      { name: 'Begeistern', value: null },
      { name: 'Lügen', value: null },
    ],
  },
];
